/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csl_DictSearch_DictSearch */

#ifndef _Included_csl_DictSearch_DictSearch
#define _Included_csl_DictSearch_DictSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     csl_DictSearch_DictSearch
 * Method:    native_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_csl_DictSearch_DictSearch_native_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     csl_DictSearch_DictSearch
 * Method:    native_query
 * Signature: (Ljava/lang/String;Lcsl/DictSearch/DictSearch/ResultReceiver;)J
 */
JNIEXPORT void JNICALL Java_csl_DictSearch_DictSearch_native_1query
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
