/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CandExtractor */

#ifndef _Included_CandExtractor
#define _Included_CandExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CandExtractor
 * Method:    initNativeCandExtractor
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CandExtractor_initNativeCandExtractor
  (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     CandExtractor
 * Method:    destroyNativeCandExtractor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CandExtractor_destroyNativeCandExtractor
  (JNIEnv *, jobject);

/*
 * Class:     CandExtractor
 * Method:    nativeQuery
 * Signature: (Ljava/lang/String;ILCandReceiver;)V
 */
JNIEXPORT void JNICALL Java_CandExtractor_nativeQuery
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     CandExtractor
 * Method:    test
 * Signature: (LCandExtractor;)V
 */
JNIEXPORT void JNICALL Java_CandExtractor_test
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CandExtractor
 * Method:    lookup
 * Signature: (Ljava/lang/String;Ljava/lang/Float;)Z
 */
JNIEXPORT jboolean JNICALL Java_CandExtractor_lookup
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
