FSDict: fsdict::DictSearch::AbstractDictModule Class Reference
fsdict::DictSearch::AbstractDictModule Class Reference
#include <DictSearch.h>
Public Member Functions
AbstractDictModule (DictSearch &myDictSearch, std::wstring const &name, size_t cascadeRank)
DictSearch & getMyDictSearch ()
size_t getDLevByWordlength (size_t wordLength) const
get the lev-distance threshold given a word length
Global::CaseMode getCaseMode () const
size_t getMaxNrOfPatterns () const
returns the current setting for the upper bound of applied variant patterns
size_t getDLevHypothetic () const
std::wstring const & getName () const
returns the DictModule's name
Setters
void setDLev (size_t dLev)
Sets a static Levenshtein distance threshold for approximate lookup.
void setDLevWordlengths (size_t wordlength_1, size_t wordlength_2, size_t wordlength_3)
configures the approximate lookup in a way that the lev-distance bound (see setDLev()) depends on the word length of the query word.
void setDLevWordlengths ()
Sets sensible standard values for word-length dependent distance bounds for approximate search.
void setMinNrOfPatterns (size_t min)
sets a new value for the upper bound of applied variant patterns
void setMaxNrOfPatterns (size_t max)
sets a new value for the upper bound of applied variant patterns
void setDLevHypothetic (size_t dlev)
sets a new value for the upper bound of applied variant patterns
Public Member Functions inherited from fsdict::DictSearch::iDictModule
iDictModule (size_t cascadeRank=0)
virtual ~iDictModule ()
A virtual destructor for a virtual class.
virtual bool query (std::wstring const &query, iResultReceiver *answers)=0
Allows to query the iDctModule with some string.
size_t getCascadeRank () const
void setPriority (int p)
Set a value in the range [0;100].
int getPriority () const
returns a value between 0 and 100 to indicate the DictModule's priority as compared to others This is used for a rough sorting order of all answers.
Constructor & Destructor Documentation
fsdict::DictSearch::AbstractDictModule::AbstractDictModule (DictSearch & myDictSearch, std::wstring const & name, size_t cascadeRank) inline
Member Function Documentation
void fsdict::DictSearch::AbstractDictModule::setDLev (size_t dLev) inline
Sets a static Levenshtein distance threshold for approximate lookup.
If you set a value other than 0 here (which is the default value), the lookup algorithm will, for a query word w, return all words w' of the dictionary where the levenshtein distance between w and w' does not exceed the given boundary.
Referenced by AbstractDictModule(), fsdict::DictSearch::AnnotatedDictModule::AnnotatedDictModule(), fsdict::DictSearch::DictModule::DictModule(), fsdict::DictSearch::readConfiguration(), fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), and fsdict::TestDictSearch::testDLev().
void fsdict::DictSearch::AbstractDictModule::setDLevWordlengths (size_t wordlength_1, size_t wordlength_2, size_t wordlength_3) inline
configures the approximate lookup in a way that the lev-distance bound (see setDLev()) depends on the word length of the query word.
Parameters
wordlength_1 minimal word length for a query to be searched for with distance bound 1
wordlength_2 minimal word length for a query to be searched for with distance bound 2
wordlength_3 minimal word length for a query to be searched for with distance bound 3
A search with distance bound n naturally also returns candidates with distances smaller than n. For example, searching with distance 2 will in general return candidates with distance 0,1,2. That's why it makes no sense to assign, e.g. wordlength_2=8 and wordlength_1=6. Whenever wordlength_i is smaller than wordlength_i-1 an exception is thrown.
Referenced by fsdict::DictSearch::readConfiguration(), fsdict::TestDictSearch::smokeTest(), and fsdict::TestDictSearch::testDLev().
void fsdict::DictSearch::AbstractDictModule::setDLevWordlengths () inline
Sets sensible standard values for word-length dependent distance bounds for approximate search.
lev. distance 1 for wordslengths 1-6
lev. distance 2 for words of length 7 and longer
See Also
setDLevWordlengths(size_t wordlength_1, size_t wordlength_2, size_t wordlength_3), setDLev
void fsdict::DictSearch::AbstractDictModule::setMinNrOfPatterns (size_t min) inline
sets a new value for the upper bound of applied variant patterns
void fsdict::DictSearch::AbstractDictModule::setMaxNrOfPatterns (size_t max) inline
sets a new value for the upper bound of applied variant patterns
Referenced by fsdict::DictSearch::readConfiguration(), and fsdict::TestDictSearch::smokeTest().
void fsdict::DictSearch::AbstractDictModule::setDLevHypothetic (size_t dlev) inline
sets a new value for the upper bound of applied variant patterns
Referenced by fsdict::DictSearch::readConfiguration(), and fsdict::TestDictSearch::smokeTest().
DictSearch& fsdict::DictSearch::AbstractDictModule::getMyDictSearch () inline
Referenced by fsdict::DictSearch::DictModule::query().
size_t fsdict::DictSearch::AbstractDictModule::getDLevByWordlength (size_t wordLength) const inline
get the lev-distance threshold given a word length
Referenced by fsdict::DictSearch::AnnotatedDictModule::query(), fsdict::DictSearch::DictModule::query(), and fsdict::TestDictSearch::testDLev().
Global::CaseMode fsdict::DictSearch::AbstractDictModule::getCaseMode () const inline
size_t fsdict::DictSearch::AbstractDictModule::getMaxNrOfPatterns () const inline
returns the current setting for the upper bound of applied variant patterns
Referenced by fsdict::DictSearch::DictModule::query().
size_t fsdict::DictSearch::AbstractDictModule::getDLevHypothetic () const inline
Referenced by fsdict::DictSearch::DictModule::query().
std::wstring const& fsdict::DictSearch::AbstractDictModule::getName () const inline virtual
returns the DictModule's name
Implements fsdict::DictSearch::iDictModule.
The documentation for this class was generated from the following file:
fsdict/DictSearch/DictSearch.h