FSDict: fsdict::PosPattern Class Reference
fsdict::PosPattern Class Reference
the Pattern class is simply enriched by a member variable indicating a position inside a word
#include <PosPattern.h>
Public Member Functions
PosPattern ()
creates an empty Pattern at position 0
PosPattern (const std::wstring &left, const std::wstring &right, size_t position)
bool operator== (PosPattern const &other) const
void clear ()
bool empty () const
returns if pattern is "empty"
size_t getPosition () const
void setPosition (size_t p)
void print (std::wostream &os=std::wcout) const
std::wstring toString () const
size_t parseFromString (std::wstring const &str, size_t offset=0)
reads Pattern data structure from the given string.
Public Member Functions inherited from fsdict::Pattern
Pattern ()
Constructs an empty pattern with left == right == "".
Pattern (const std::wstring &left, const std::wstring &right)
A very self-explanatory constructor.
bool operator== (const Pattern &other) const
bool operator!= (const Pattern &other) const
bool operator< (const Pattern &other) const
creates an order relation on Pattern objects, mainly to be able t ostore them in std::set etc.
void clear ()
const std::wstring & getLeft () const
get the left side of the pattern
const std::wstring & getRight () const
get the right side of the pattern
bool empty () const
returns if pattern is "empty"
void setLeft (std::wstring const &left)
void setRight (std::wstring const &right)
void strip ()
Get rid of wordBegin- and wordEnd-markers.
void print (std::wostream &os=std::wcout) const
std::wstring toString () const
Additional Inherited Members
Static Public Member Functions inherited from fsdict::Pattern
static void setLeftRightDelimiter (wchar_t c)
Static Public Attributes inherited from fsdict::Pattern
static wchar_t leftRightDelimiter_ = L':'
This value determines which symbol is used as delimiter between left and right pattern side.
Detailed Description
the Pattern class is simply enriched by a member variable indicating a position inside a word
Constructor & Destructor Documentation
fsdict::PosPattern::PosPattern () inline
creates an empty Pattern at position 0
fsdict::PosPattern::PosPattern (const std::wstring & left, const std::wstring & right, size_t position) inline
Member Function Documentation
bool fsdict::PosPattern::operator== (PosPattern const & other) const inline
void fsdict::PosPattern::clear () inline
Referenced by fsdict::Instruction::parseFromString().
bool fsdict::PosPattern::empty () const inline
returns if pattern is "empty"
size_t fsdict::PosPattern::getPosition () const inline
Referenced by operator==(), print(), and fsdict::TestPattern::testPosPattern().
void fsdict::PosPattern::setPosition (size_t p) inline
Referenced by parseFromString().
void fsdict::PosPattern::print (std::wostream & os = std::wcout) const inline
Referenced by std::operator<<(), and toString().
std::wstring fsdict::PosPattern::toString () const inline
Referenced by fsdict::TestPattern::testPosPattern().
size_t fsdict::PosPattern::parseFromString (std::wstring const & str, size_t offset = 0) inline
reads Pattern data structure from the given string.
Parameters
offset start at this position of the string. Default is 0
Returns
A new offset pointing to the first character not used for the parse
Referenced by fsdict::Instruction::parseFromString(), and fsdict::TestPattern::testPosPattern().
The documentation for this class was generated from the following file:
fsdict/Pattern/PosPattern.h