FSDict: fsdict::DictSearch Class Reference
fsdict::DictSearch Class Reference
fsdict::DictSearch is a combined interface for approximate dictionary lookup in the context of historical language.
#include <DictSearch.h>
Classes
class AbstractDictModule
class AnnotatedDictModule
This implementation of DictSearch::iDictModule is used for lexica containing historical variants, including a specification of all possible links to modern words.
class CandidateSet
CandidateSet is a simple container to collect candidates/interpretations from either a Vaam or a fsdict::MSMatch object.
class DictModule
An object of this type handles one dictionary that is to be used with DictSearch, and allows search with approximate search and approximate/hypothetic search.
class iDictModule
All classes that are supposed to contribute to the answer set of a DictSearch query have to implement this interface.
class Interpretation
This is a specialisation of fsdict::Interpretation, tailored to store additional information added by DictSearch.
class iResultReceiver
Whoever wants to receive results from DictSearch, has to implement these two interfaces.
Public Types
typedef FBDic Dict_t
typedef MinDic VaamDict_t
Public Member Functions
Constructor/ Destructor
DictSearch ()
~DictSearch ()
Configuration
void readConfiguration (char const *configFile)
Load a configuration from a configFile.
void readConfiguration (INIConfig const &iniConf)
Load a configuration from an existing INIConfig object.
void initHypothetic (char const *patternFile)
initialise the hypothetic dictionary.
DictModule & addDictModule (std::wstring const &name, std::string const &dicFile, size_t cascadeRank=0)
DictModule & addDictModule (std::wstring const &name, Dict_t const &dicRef, size_t cascadeRank=0)
AnnotatedDictModule & addAnnotatedDictModule (AnnotatedDictModule *newDM)
Adds an AnnotatedDictModule to DictSearch.
void addExternalDictModule (iDictModule &extModule)
bool hasDictModules () const
A simple check if any DictModules are activated.
bool hasHypothetic () const
Lookup
bool query (std::wstring const &query, iResultReceiver *answers)
Static Public Attributes
static const size_t INFINITE = (size_t)-1
Detailed Description
fsdict::DictSearch is a combined interface for approximate dictionary lookup in the context of historical language.
A special DictSearch Manual page was prepared for this module. You might want to have a look at it before reading this class reference.
fsdict::DictSearch is a combined interface for a number of modules of the package. The scenario is that the users specify a modern as well as a historical dictionary to perform exact or approximate dictionary lookups. A third component is what we call the "hypothetic dictionary", containing all orthographical variants that can possibly be derived from some word of the modern dictionary and the application of some "orthographical variant patterns". These patterns are simple rewrite rules and can be specified by the user.
For a query word w the users receive as answer a set of words, containing exact and approximate matches for either of the three dictionaries. In the usual application this answer set is understood as set of correction candidates for a (probably garbled) token w. The task of ranking these candidates is explicitly out of the scope of fsdict::DictSearch: To decide for a correction candidate, various other techniques for channel and language modelling have to be taken into account.
Author
Ulrich Reffleuli@c.nosp@m.is.u.nosp@m.ni-mu.nosp@m.ench.nosp@m.en.de, 2008
Member Typedef Documentation
typedef FBDic fsdict::DictSearch::Dict_t
typedef MinDic fsdict::DictSearch::VaamDict_t
Constructor & Destructor Documentation
fsdict::DictSearch::DictSearch ()
fsdict::DictSearch::~DictSearch ()
Member Function Documentation
void fsdict::DictSearch::readConfiguration (char const * configFile)
Load a configuration from a configFile.
Referenced by main().
void fsdict::DictSearch::readConfiguration (INIConfig const & iniConf)
Load a configuration from an existing INIConfig object.
void fsdict::DictSearch::initHypothetic (char const * patternFile)
initialise the hypothetic dictionary.
Parameters
patternFile A file containing a list of rewrite patterns. Consult fsdict::PatternSet for details
At the moment you can NOT change the pattern set afterwards. Please notify the developers if you need such a feature.
Referenced by readConfiguration(), and fsdict::TestDictSearch::smokeTest().
DictSearch::DictModule & fsdict::DictSearch::addDictModule (std::wstring const & name, std::string const & dicFile, size_t cascadeRank = 0)
Referenced by readConfiguration(), fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), fsdict::TestDictSearch::testCaseMode(), and fsdict::TestDictSearch::testDLev().
DictSearch::DictModule & fsdict::DictSearch::addDictModule (std::wstring const & name, Dict_t const & dicRef, size_t cascadeRank = 0)
DictSearch::AnnotatedDictModule & fsdict::DictSearch::addAnnotatedDictModule (AnnotatedDictModule * newDM)
Adds an AnnotatedDictModule to DictSearch.
This module will be deleted by DictSearch, so be sure to create it on the heap and not to delete it yourself.
Parameters
newDM
Returns
Referenced by readConfiguration().
void fsdict::DictSearch::addExternalDictModule (iDictModule & extModule)
Referenced by fsdict::TestDictSearch::testAnnotatedDictModule().
bool fsdict::DictSearch::hasDictModules () const
A simple check if any DictModules are activated.
This is useful to test in client programs and perhaps to give a warning,
bool fsdict::DictSearch::hasHypothetic () const
Referenced by fsdict::DictSearch::DictModule::query().
bool fsdict::DictSearch::query (std::wstring const & query, iResultReceiver * answers)
Parameters
[in] query
[out] answers
Returns
true iff at least one answer was found
Referenced by main(), fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testAnnotatedDictModule(), fsdict::TestDictSearch::testCascades(), and fsdict::TestDictSearch::testCaseMode().
Member Data Documentation
const size_t fsdict::DictSearch::INFINITE = (size_t)-1 static
Referenced by fsdict::DictSearch::AbstractDictModule::getDLevByWordlength(), fsdict::DictSearch::AbstractDictModule::setDLev(), and fsdict::DictSearch::AbstractDictModule::setDLevWordlengths().
The documentation for this class was generated from the following files:
fsdict/DictSearch/DictSearch.h
fsdict/DictSearch/DictSearch.cxx