FSDict: fsdict::MinDicString Class Reference
fsdict::MinDicString Class Reference
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
#include <MinDicString.h>
Public Types
typedef MinDic MinDic_t
Public Types inherited from fsdict::MinDic<>
typedef TransTable
< TT_PERFHASH, uint16_t > TransTable_t
typedef int AnnType_t
The datatype of the annotation that comes with each dictionary entry.
Public Member Functions
MinDicString ()
MinDicString (char const *dicFile)
Create a MinDicString object and load a dic from the specified file.
void setKeyValueDelimiter (uchar c)
uchar const * lookup (wchar_t *key) const
uchar const * getAnnByPerfHashValue (size_t perfHashValue) const
return the string value annotated to the entry with the given perfect hash value
uchar const * getAnnByOffset (size_t offset) const
return the string value at the specified offset in the annotation buffer
void loadFromFile (char const *dicFile)
void loadFromStream (FILE *fi)
void writeToFile (char const *dicFile) const
void writeToStream (FILE *fo) const
void initConstruction ()
void finishConstruction ()
void compileDic (const char *lexFile)
void printDic () const
void doAnalysis () const
Public Member Functions inherited from fsdict::MinDic<>
MinDic (const char *dicFile=0)
Create a new MinDic.
MinDic (MinDic< AnnType_t > const &other)
The copy constructor is NOT IMPLEMENTED at the moment.
bool lookup (const wchar_t *key, AnnType_t *annotation=0) const
Use this function to do a convenient lookup.
bool lookup (std::wstring const &key, AnnType_t *annotation=0) const
bool hasPrefix (std::wstring const &prefix) const
bool getAnnotation (const wchar_t *key, AnnType_t *annotation) const
this method is renamed to lookup()
const AnnType_t & getAnnotation (size_t perfHashValue) const
State getRootState () const
Get a State object of the automaton's root/ start state.
TokenIterator tokensBegin () const
TokenIterator tokensEnd () const
void loadFromFile (const char *binFile)
Load a compiled MinDic from hard disk.
void loadFromStream (FILE *fi)
Load a compiled MinDic from an open file stream.
void writeToFile (char const *binFile) const
dump MinDic automaton to a file in binary form.
void writeToStream (FILE *fo) const
dump MinDic automaton to an open file stream
void compileDic (const char *txtFile)
The funtion that actually executes the computation of the trie.
void parseAnnotation (std::wstring *str, AnnType_t *annotation) const
This method parses an input line (provided as param str).
void initConstruction ()
prepares the object for construction of a new MinDic.
void addToken (const wchar_t *input, const AnnType_t &value)
Add one new entry.
void finishConstruction ()
Finalize the construction Call after calling addToken() for the last time.
void printDic () const
void printDic (StateId_t initState) const
extracts the trie to stdout
size_t getNrOfKeys () const
void doAnalysis () const
int getFirstAnn (StateId_t state)
This method from TransTable is blocked for MinDic, not implemented here!
Public Member Functions inherited from fsdict::iDictionary< int >
virtual ~iDictionary ()
Additional Inherited Members
Protected Member Functions inherited from fsdict::MinDic<>
const AnnType_t & annotationsAt (size_t n) const
Detailed Description
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
Currently the keys of the dictionaries are represented as wide strings, while the annotations are stored as utf-8 sequences. This makes the data structure smaller, and in some contexts also faster. But, now that the whole rest of the library has been changed to wide strings, this is definitely a bit out-dated.
Todo:
Change to consistent use of wstring
Author
Uli Reffle
Date
2006-2010
Member Typedef Documentation
typedef MinDic fsdict::MinDicString::MinDic_t
Constructor & Destructor Documentation
fsdict::MinDicString::MinDicString () inline
fsdict::MinDicString::MinDicString (char const * dicFile) inline
Create a MinDicString object and load a dic from the specified file.
Member Function Documentation
void fsdict::MinDicString::setKeyValueDelimiter (uchar c) inline
Referenced by main().
uchar const* fsdict::MinDicString::lookup (wchar_t * key) const inline
Referenced by main().
uchar const* fsdict::MinDicString::getAnnByPerfHashValue (size_t perfHashValue) const inline
return the string value annotated to the entry with the given perfect hash value
uchar const* fsdict::MinDicString::getAnnByOffset (size_t offset) const inline
return the string value at the specified offset in the annotation buffer
void fsdict::MinDicString::loadFromFile (char const * dicFile) inline
Referenced by main().
void fsdict::MinDicString::loadFromStream (FILE * fi) inline
void fsdict::MinDicString::writeToFile (char const * dicFile) const inline
Referenced by main().
void fsdict::MinDicString::writeToStream (FILE * fo) const inline
void fsdict::MinDicString::initConstruction () inline
void fsdict::MinDicString::finishConstruction () inline
void fsdict::MinDicString::compileDic (const char * lexFile) inline
Referenced by main().
void fsdict::MinDicString::printDic () const inline
Referenced by main().
void fsdict::MinDicString::doAnalysis () const inline
Referenced by main().
The documentation for this class was generated from the following file:
fsdict/MinDicString/MinDicString.h