FSDict: fsdict::Interpretation Class Reference
fsdict::Interpretation Class Reference
This class is something like a container class to store one interpretation of some string as the spelling variant (and/or erroneous variant) of some other string.
#include <Interpretation.h>
Public Member Functions
bool operator< (Interpretation const &other) const
set up a comparison based on the sum of levenshtein or pattern edits.
size_t parseFromString (std::wstring const &str, size_t offset=0)
Constructors/ Destructors
Interpretation ()
Getters
std::wstring & getWord ()
returns a reference to the plain string
std::wstring const & getWord () const
returns a const reference to the plain string
std::wstring const & getBaseWord () const
returns the so-called baseWord from the dictionary, that was changed into a variant with the given Instruction
size_t getLevDistance () const
returns the levenshtein distance to the query
size_t getBaseWordScore () const
returns the score that was annotated with the baseWord in the dictionary.
Instruction & getInstruction ()
returns the instruction that was used to turn baseWord into word
Instruction const & getInstruction () const
const version of getInstruction()
Instruction & getHistInstruction ()
More verbose name for getInstruction().
Instruction const & getHistInstruction () const
const version of getHistInstruction()
Setters
void setWord (std::wstring const &w)
void setBaseWord (std::wstring const &w)
void setLevDistance (size_t dist)
void setBaseWordScore (size_t score)
void clear ()
erase all values from the object and bring it into a state as if just created.
Pretty-print
void print (std::wostream &os=std::wcout) const
prints a string-representation of the interpretation to stdout or to another std::wstream specified as argument.
std::wstring toString () const
void print_v2 (std::wostream &os=std::wcout) const
prints another useful format of the interpretation, more in the INL tradition
Detailed Description
This class is something like a container class to store one interpretation of some string as the spelling variant (and/or erroneous variant) of some other string.
Usually this class will be the answer object (or part thereof) of a query to ErrDic or Vaam.
Author
Ulrich Reffle 2008
Constructor & Destructor Documentation
fsdict::Interpretation::Interpretation ()
Member Function Documentation
bool fsdict::Interpretation::operator< (Interpretation const & other) const
set up a comparison based on the sum of levenshtein or pattern edits.
Give the levenshtein operations a marginally higher punishment, so that if the sums are equal, the one with less lev. operations and more pattern operations will win.
std::wstring & fsdict::Interpretation::getWord ()
returns a reference to the plain string
Referenced by operator<(), fsdict::DictSearch::Interpretation::operator<(), fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), fsdict::TestDictSearch::testCaseMode(), and fsdict::TestPattern::testInterpretation().
std::wstring const & fsdict::Interpretation::getWord () const
returns a const reference to the plain string
std::wstring const & fsdict::Interpretation::getBaseWord () const
returns the so-called baseWord from the dictionary, that was changed into a variant with the given Instruction
If the instruction is empty, then getWord() == getBaseWord()
Referenced by print(), and fsdict::TestPattern::testInterpretation().
size_t fsdict::Interpretation::getLevDistance () const
returns the levenshtein distance to the query
Referenced by operator<(), fsdict::DictSearch::Interpretation::operator<(), print(), and fsdict::TestPattern::testInterpretation().
size_t fsdict::Interpretation::getBaseWordScore () const
returns the score that was annotated with the baseWord in the dictionary.
Referenced by fsdict::TestPattern::testInterpretation().
Instruction & fsdict::Interpretation::getInstruction ()
returns the instruction that was used to turn baseWord into word
Deprecated:
Use getHistInstruction instead!
Referenced by operator<(), fsdict::DictSearch::Interpretation::operator<(), fsdict::TestDictSearch::smokeTest(), and fsdict::TestDictSearch::testCaseMode().
Instruction const & fsdict::Interpretation::getInstruction () const
const version of getInstruction()
Deprecated:
Use getHistInstruction instead!
Instruction & fsdict::Interpretation::getHistInstruction ()
More verbose name for getInstruction().
Referenced by fsdict::TestPattern::testInterpretation().
Instruction const & fsdict::Interpretation::getHistInstruction () const
const version of getHistInstruction()
void fsdict::Interpretation::setWord (std::wstring const & w)
Referenced by parseFromString(), fsdict::DictSearch::CandidateSet::receive(), and fsdict::TestPattern::testInterpretation().
void fsdict::Interpretation::setBaseWord (std::wstring const & w)
Referenced by parseFromString(), fsdict::DictSearch::CandidateSet::receive(), and fsdict::TestPattern::testInterpretation().
void fsdict::Interpretation::setLevDistance (size_t dist)
Referenced by fsdict::DictSearch::CandidateSet::receive(), and fsdict::TestPattern::testInterpretation().
void fsdict::Interpretation::setBaseWordScore (size_t score)
Referenced by fsdict::DictSearch::CandidateSet::receive().
void fsdict::Interpretation::clear ()
erase all values from the object and bring it into a state as if just created.
Referenced by fsdict::TestPattern::testInterpretation().
size_t fsdict::Interpretation::parseFromString (std::wstring const & str, size_t offset = 0)
Referenced by fsdict::TestPattern::testInterpretation().
void fsdict::Interpretation::print (std::wostream & os = std::wcout) const
prints a string-representation of the interpretation to stdout or to another std::wstream specified as argument.
Referenced by std::operator<<(), fsdict::DictSearch::Interpretation::print(), and toString().
std::wstring fsdict::Interpretation::toString () const
Referenced by operator<(), fsdict::TestPattern::testInterpretation(), and fsdict::DictSearch::Interpretation::toString().
void fsdict::Interpretation::print_v2 (std::wostream & os = std::wcout) const
prints another useful format of the interpretation, more in the INL tradition
The documentation for this class was generated from the following files:
fsdict/Pattern/Interpretation.h
fsdict/Pattern/Interpretation.cxx