FSDict: fsdict::DictSearch::Interpretation Class Reference
fsdict::DictSearch::Interpretation Class Reference
This is a specialisation of fsdict::Interpretation, tailored to store additional information added by DictSearch.
#include <DictSearch.h>
Public Member Functions
Interpretation ()
Interpretation (fsdict::Interpretation const &interpretation, iDictModule const &dm)
bool operator< (Interpretation const &other) const
set up a comparison based on the sum of levenshtein or pattern edits.
void setDictModule (iDictModule const &dictModule)
specify the dictModule which the interpretation comes from
iDictModule const & getDictModule () const
get a pointer to the dictModule which the interpretation came from
void print (std::wostream &os=std::wcout) const
std::wstring toString () const
Public Member Functions inherited from fsdict::Interpretation
bool operator< (Interpretation const &other) const
set up a comparison based on the sum of levenshtein or pattern edits.
size_t parseFromString (std::wstring const &str, size_t offset=0)
Interpretation ()
std::wstring & getWord ()
returns a reference to the plain string
std::wstring const & getWord () const
returns a const reference to the plain string
std::wstring const & getBaseWord () const
returns the so-called baseWord from the dictionary, that was changed into a variant with the given Instruction
size_t getLevDistance () const
returns the levenshtein distance to the query
size_t getBaseWordScore () const
returns the score that was annotated with the baseWord in the dictionary.
Instruction & getInstruction ()
returns the instruction that was used to turn baseWord into word
Instruction const & getInstruction () const
const version of getInstruction()
Instruction & getHistInstruction ()
More verbose name for getInstruction().
Instruction const & getHistInstruction () const
const version of getHistInstruction()
void setWord (std::wstring const &w)
void setBaseWord (std::wstring const &w)
void setLevDistance (size_t dist)
void setBaseWordScore (size_t score)
void clear ()
erase all values from the object and bring it into a state as if just created.
void print (std::wostream &os=std::wcout) const
prints a string-representation of the interpretation to stdout or to another std::wstream specified as argument.
std::wstring toString () const
void print_v2 (std::wostream &os=std::wcout) const
prints another useful format of the interpretation, more in the INL tradition
Detailed Description
This is a specialisation of fsdict::Interpretation, tailored to store additional information added by DictSearch.
Constructor & Destructor Documentation
fsdict::DictSearch::Interpretation::Interpretation () inline
fsdict::DictSearch::Interpretation::Interpretation (fsdict::Interpretation const & interpretation, iDictModule const & dm) inline
Member Function Documentation
bool fsdict::DictSearch::Interpretation::operator< (Interpretation const & other) const inline
set up a comparison based on the sum of levenshtein or pattern edits.
Give the levenshtein operations a marginally higher punishment, so that if the sums are equal, the one with less lev. operations and more pattern operations will win.
void fsdict::DictSearch::Interpretation::setDictModule (iDictModule const & dictModule) inline
specify the dictModule which the interpretation comes from
See Also
dictModule_
iDictModule const& fsdict::DictSearch::Interpretation::getDictModule () const inline
get a pointer to the dictModule which the interpretation came from
See Also
dictModule_
Referenced by operator<(), print(), and toString().
void fsdict::DictSearch::Interpretation::print (std::wostream & os = std::wcout) const inline
Referenced by std::operator<<().
std::wstring fsdict::DictSearch::Interpretation::toString () const inline
The documentation for this class was generated from the following file:
fsdict/DictSearch/DictSearch.h