FSDict: fsdict::DictSearch::iDictModule Class Reference
fsdict::DictSearch::iDictModule Class Reference abstract
All classes that are supposed to contribute to the answer set of a DictSearch query have to implement this interface.
#include <DictSearch.h>
Public Member Functions
iDictModule (size_t cascadeRank=0)
virtual ~iDictModule ()
A virtual destructor for a virtual class.
virtual bool query (std::wstring const &query, iResultReceiver *answers)=0
Allows to query the iDctModule with some string.
virtual std::wstring const & getName () const =0
returns a string to identify the DictModule
size_t getCascadeRank () const
void setPriority (int p)
Set a value in the range [0;100].
int getPriority () const
returns a value between 0 and 100 to indicate the DictModule's priority as compared to others This is used for a rough sorting order of all answers.
Detailed Description
All classes that are supposed to contribute to the answer set of a DictSearch query have to implement this interface.
The method DictSearch::addExternalDictModule() allows to add such objects to the process.
One implementation of this interface is DictSearch's sub-class DictModule
Constructor & Destructor Documentation
fsdict::DictSearch::iDictModule::iDictModule (size_t cascadeRank = 0) inline
virtual fsdict::DictSearch::iDictModule::~iDictModule () inline virtual
A virtual destructor for a virtual class.
Member Function Documentation
virtual bool fsdict::DictSearch::iDictModule::query (std::wstring const & query, iResultReceiver * answers) pure virtual
Allows to query the iDctModule with some string.
The iDictModule is expected to add all its answers/ interpretations to the CandidateSet that is passed.
Returns
true iff at least one answer was found
Implemented in fsdict::DictSearch::DictModule, and fsdict::DictSearch::AnnotatedDictModule.
virtual std::wstring const& fsdict::DictSearch::iDictModule::getName () const pure virtual
returns a string to identify the DictModule
Implemented in fsdict::DictSearch::AbstractDictModule.
Referenced by fsdict::DictSearch::Interpretation::print(), and fsdict::DictSearch::Interpretation::toString().
size_t fsdict::DictSearch::iDictModule::getCascadeRank () const inline
Referenced by fsdict::DictSearch::addAnnotatedDictModule(), fsdict::DictSearch::addDictModule(), and fsdict::DictSearch::addExternalDictModule().
void fsdict::DictSearch::iDictModule::setPriority (int p) inline
Set a value in the range [0;100].
This value decides which candidate to rank higher if the other criteria (nr of hist/ocr patterns) are equal.
Referenced by fsdict::DictSearch::readConfiguration().
int fsdict::DictSearch::iDictModule::getPriority () const inline
returns a value between 0 and 100 to indicate the DictModule's priority as compared to others This is used for a rough sorting order of all answers.
Referenced by fsdict::DictSearch::Interpretation::operator<().
The documentation for this class was generated from the following file:
fsdict/DictSearch/DictSearch.h