FSDict: fsdict::PatternWeights Class Reference
fsdict::PatternWeights Class Reference
#include <PatternWeights.h>
Classes
class PatternType
a PatternType describes the relation of the lengths of both pattern sides.
Public Types
typedef std::map
< fsdict::Pattern, double >
::iterator PatternIterator
typedef std::map
< fsdict::Pattern, double >
::const_iterator const_PatternIterator
Public Member Functions
PatternWeights ()
virtual ~PatternWeights ()
virtual void clear ()
Removes all the weights and defaults.
virtual void clearExplicitWeights ()
Removes all the explicit weights, but leaves the defaults intact.
size_t size () const
double getWeight (const fsdict::Pattern &pattern) const
void setWeight (const fsdict::Pattern &pattern, double weight)
set a new weight for a pattern
double getDefault (PatternType const &patternType) const
void setDefault (PatternType const &patternType, double weight)
void setSmartMerge (bool t=true)
If "smartMerge" is activated, it will override the default settings (set via setDefault()) and return the weight UNDEF for all merges and splits of the form "xy <-> x" and "xy <-> y".
const_PatternIterator patternsBegin () const
PatternIterator patternsBegin ()
const_PatternIterator patternsEnd () const
PatternIterator patternsEnd ()
void print (std::wostream &str=std::wcout) const
prints the pattern weights
void loadFromFile (const char *patternFile)
void writeToFile (const char *patternFile) const
void writeToXML (std::wostream &os) const
void writeToXML (const char *xmlFile) const
void sortToVector (std::vector< std::pair< fsdict::Pattern, double > > *vec) const
Static Public Attributes
static const int UNDEF = -1
Detailed Description
Author
Ulrich Reffle uli@c.nosp@m.is.u.nosp@m.ni-mu.nosp@m.ench.nosp@m.en.de
Date
2009
Member Typedef Documentation
typedef std::map< fsdict::Pattern, double >::iterator fsdict::PatternWeights::PatternIterator
typedef std::map< fsdict::Pattern, double >::const_iterator fsdict::PatternWeights::const_PatternIterator
Constructor & Destructor Documentation
fsdict::PatternWeights::PatternWeights ()
virtual fsdict::PatternWeights::~PatternWeights () inline virtual
Member Function Documentation
void fsdict::PatternWeights::clear () virtual
Removes all the weights and defaults.
Does NOT change the setting of the smartMerge mode.
Referenced by fsdict::TestComputeInstruction::testBasics(), and fsdict::TestPattern::testPatternProbabilities().
void fsdict::PatternWeights::clearExplicitWeights () virtual
Removes all the explicit weights, but leaves the defaults intact.
Does NOT change the setting of the smartMerge mode.
size_t fsdict::PatternWeights::size () const inline
double fsdict::PatternWeights::getWeight (const fsdict::Pattern & pattern) const
Returns
the weight for a given pattern, or PatternWeights::UNDEF if the pattern is not known
Referenced by fsdict::ComputeInstruction::computeInstruction(), fsdict::TestPatternWeights::testBasics(), fsdict::TestPatternWeights::testFileDump(), and fsdict::TestPattern::testPatternProbabilities().
void fsdict::PatternWeights::setWeight (const fsdict::Pattern & pattern, double weight)
set a new weight for a pattern
Referenced by fsdict::TestComputeInstruction::testBasics(), fsdict::TestPatternWeights::testBasics(), fsdict::TestPatternWeights::testFileDump(), and fsdict::TestPattern::testPatternProbabilities().
double fsdict::PatternWeights::getDefault (PatternType const & patternType) const
Referenced by getWeight().
void fsdict::PatternWeights::setDefault (PatternType const & patternType, double weight)
Referenced by fsdict::TestComputeInstruction::testBasics(), fsdict::TestPatternWeights::testBasics(), fsdict::TestPattern::testPatternProbabilities(), and fsdict::TestComputeInstruction::testProfilerSetting().
void fsdict::PatternWeights::setSmartMerge (bool t = true)
If "smartMerge" is activated, it will override the default settings (set via setDefault()) and return the weight UNDEF for all merges and splits of the form "xy <-> x" and "xy <-> y".
It does NOT override the specific weights added via setWeight()
Referenced by fsdict::TestComputeInstruction::testBasics().
const_PatternIterator fsdict::PatternWeights::patternsBegin () const inline
Referenced by writeToXML().
PatternIterator fsdict::PatternWeights::patternsBegin () inline
const_PatternIterator fsdict::PatternWeights::patternsEnd () const inline
Referenced by writeToXML().
PatternIterator fsdict::PatternWeights::patternsEnd () inline
void fsdict::PatternWeights::print (std::wostream & str = std::wcout) const
prints the pattern weights
void fsdict::PatternWeights::loadFromFile (const char * patternFile)
Referenced by fsdict::TestPatternWeights::testFileDump().
void fsdict::PatternWeights::writeToFile (const char * patternFile) const
Referenced by fsdict::TestPatternWeights::testFileDump().
void fsdict::PatternWeights::writeToXML (std::wostream & os) const
Referenced by writeToXML().
void fsdict::PatternWeights::writeToXML (const char * xmlFile) const
void fsdict::PatternWeights::sortToVector (std::vector< std::pair< fsdict::Pattern, double > > * vec) const
Referenced by print(), and writeToFile().
Member Data Documentation
const int fsdict::PatternWeights::UNDEF = -1 static
Referenced by fsdict::ComputeInstruction::computeInstruction(), getDefault(), getWeight(), setDefault(), setWeight(), fsdict::TestComputeInstruction::testBasics(), fsdict::TestPatternWeights::testBasics(), fsdict::TestPattern::testPatternProbabilities(), and fsdict::TestComputeInstruction::testProfilerSetting().
The documentation for this class was generated from the following files:
fsdict/Pattern/PatternWeights.h
fsdict/Pattern/PatternWeights.cxx