FSDict: fsdict::ResultSet Class Reference
fsdict::ResultSet Class Reference
A container class for candidate sets extracted by a LevFilter object.
#include <ResultSet.h>
Classes
class Item
Public Member Functions
ResultSet ()
size_t getSize () const
returns the current size of the ResultSet
void receive (const wchar_t *str, int levDistance, int annotation)
add another item to the ResultSet
void reset ()
delete all items from the list
const Item & operator[] (int i) const
void sort ()
void sortUnique ()
Public Member Functions inherited from fsdict::LevFilter::CandidateReceiver
virtual ~CandidateReceiver ()
Static Public Member Functions
static bool cmp (const Item *a, const Item *b)
static bool is_equal (const Item *a, const Item *b)
Detailed Description
A container class for candidate sets extracted by a LevFilter object.
Author
Uli Reffle
Date
2006
Constructor & Destructor Documentation
fsdict::ResultSet::ResultSet () inline
Member Function Documentation
size_t fsdict::ResultSet::getSize () const inline
returns the current size of the ResultSet
Returns
the current size of the ResultSet
Referenced by main().
void fsdict::ResultSet::receive (const wchar_t * str, int levDistance, int annotation) inline virtual
add another item to the ResultSet
Implements fsdict::LevFilter::CandidateReceiver.
Referenced by main().
void fsdict::ResultSet::reset () inline virtual
delete all items from the list
Implements fsdict::LevFilter::CandidateReceiver.
Referenced by ResultSet().
const Item& fsdict::ResultSet::operator[] (int i) const inline
static bool fsdict::ResultSet::cmp (const Item * a, const Item * b) inline static
Referenced by sort().
static bool fsdict::ResultSet::is_equal (const Item * a, const Item * b) inline static
Referenced by sortUnique().
void fsdict::ResultSet::sort () inline
Referenced by sortUnique().
void fsdict::ResultSet::sortUnique () inline
The documentation for this class was generated from the following file:
fsdict/ResultSet/ResultSet.h