FSDict: fsdict::PatternGraph Class Reference
fsdict::PatternGraph Class Reference
A specialised variant of the Aho-Corasick trie to search in the set of left or right sides of a PatternSet.
#include <PatternGraph.h>
Classes
class Alphabet
class InternalState
class State
Public Types
enum Direction { FORWARD, BACKWARD }
enum IndexSide { INDEX_LEFT, INDEX_RIGHT }
typedef std::vector< std::pair
< std::wstring, size_t > > Replacements_t
Public Types inherited from fsdict::PatternSet
typedef PatternList_t::iterator iterator
typedef
PatternList_t::const_iterator const_iterator
Public Member Functions
PatternGraph (Direction dir=FORWARD, IndexSide indexSide=INDEX_LEFT)
void loadPatterns (const char *patternFile)
State getRoot () const
size_t getNrOfPatterns () const
void toDot () const
Public Member Functions inherited from fsdict::PatternSet
PatternSet ()
Pattern const & at (size_t i) const
Returns a reference pointing to the i -th position of the set.
Pattern const & stripped_at (size_t i) const
Returns a reference pointing to the i -th position of the STRIPPED set.
iterator begin ()
returns an iterator at the first pattern of the list
iterator end ()
returns a classical past-the-end iterator
void loadPatterns (const char *patternFile)
Reads a set of patterns from file patternFile.
Additional Inherited Members
Protected Types inherited from fsdict::PatternSet
typedef std::vector< Pattern > PatternList_t
Protected Member Functions inherited from fsdict::PatternSet
const PatternList_t & patternList () const
Detailed Description
A specialised variant of the Aho-Corasick trie to search in the set of left or right sides of a PatternSet.
For the sake of simplicity and efficiency, the implementation details of class PatternSet are used here: Internally we use simple size_t variables to refer to a Pattern instead of using the official and public PatternRef interface.
Author
Ulrich Reffle, 2008
Member Typedef Documentation
typedef std::vector< std::pair< std::wstring, size_t > > fsdict::PatternGraph::Replacements_t
Member Enumeration Documentation
enum fsdict::PatternGraph::Direction
Enumerator
FORWARD
BACKWARD
enum fsdict::PatternGraph::IndexSide
Enumerator
INDEX_LEFT
INDEX_RIGHT
Constructor & Destructor Documentation
fsdict::PatternGraph::PatternGraph (Direction dir = FORWARD, IndexSide indexSide = INDEX_LEFT) inline
Member Function Documentation
void fsdict::PatternGraph::loadPatterns (const char * patternFile) inline
Referenced by main(), fsdict::TestVaam::testPatternGraph(), and fsdict::TestPattern::testPatternGraph().
PatternGraph::State fsdict::PatternGraph::getRoot () const inline
Referenced by loadPatterns(), main(), fsdict::TestVaam::testPatternGraph(), and fsdict::TestPattern::testPatternGraph().
size_t fsdict::PatternGraph::getNrOfPatterns () const inline
void fsdict::PatternGraph::toDot () const inline
Referenced by main().
The documentation for this class was generated from the following file:
fsdict/Pattern/PatternGraph.h