FSDict: fsdict::CSLLocale Class Reference
fsdict::CSLLocale Class Reference
#include <CSLLocale.h>
Static Public Member Functions
static CSLLocale & Instance ()
template<typename T , typename char_type >
static T string2number (std::basic_string< char_type > const &str)
Goes the STL facet-based way to transform a string to a number.
static void wstring2string (std::wstring const &wstr, std::string &str)
converts a std::wstring into its byte-character equivalent
static void string2wstring (std::string const &str, std::wstring &wstr)
converts a std::string into its wide-character equivalent
static std::wstring string2wstring (std::string const &str)
Returns a copy of a wide string equivalent to the given narrow string.
static std::string wstring2string (std::wstring const &str)
Returns a copy of a narrow string equivalent to the given wide string.
Member Function Documentation
static CSLLocale& fsdict::CSLLocale::Instance () inline static
Referenced by fsdict::PatternWeights::loadFromFile(), string2number(), string2wstring(), fsdict::TestCSLLocale::testBasics(), fsdict::TestCSLLocale::testSTDIO(), fsdict::PatternWeights::writeToFile(), and wstring2string().
template<typename T , typename char_type > static T fsdict::CSLLocale::string2number (std::basic_string< char_type > const & str) inline static
Goes the STL facet-based way to transform a string to a number.
Parameters
[in] str a string containing the number and nothing else
Throws a fsdictException if the conversion causes problems.
static void fsdict::CSLLocale::wstring2string (std::wstring const & wstr, std::string & str) inline static
converts a std::wstring into its byte-character equivalent
Parameters
[in] wstr the input string
[out] str the output string
Referenced by fsdict::PatternSet::loadPatterns(), fsdict::Instruction::parseFromString(), and wstring2string().
static void fsdict::CSLLocale::string2wstring (std::string const & str, std::wstring & wstr) inline static
converts a std::string into its wide-character equivalent
Parameters
[in] str the input string
[out] wstr the output string
Referenced by fsdict::INIConfig::dump_ini(), iniparser_set(), main(), fsdict::Getopt::print(), fsdict::DictSearch::readConfiguration(), string2wstring(), and fsdict::TestCSLLocale::testSTDIO().
static std::wstring fsdict::CSLLocale::string2wstring (std::string const & str) inline static
Returns a copy of a wide string equivalent to the given narrow string.
static std::string fsdict::CSLLocale::wstring2string (std::wstring const & str) inline static
Returns a copy of a narrow string equivalent to the given wide string.
The documentation for this class was generated from the following files:
fsdict/CSLLocale/CSLLocale.h
fsdict/CSLLocale/CSLLocale.cxx