FSDict: fsdict::DictSearch::DictModule Class Reference
fsdict::DictSearch::DictModule Class Reference
An object of this type handles one dictionary that is to be used with DictSearch, and allows search with approximate search and approximate/hypothetic search.
#include <DictSearch.h>
Public Member Functions
DictModule (DictSearch &myDictSearch, std::wstring const &name, std::string const &dicFile, size_t cascadeRank=0)
A standard constructor using a filepath pointing to a dictionary.
DictModule (DictSearch &myDictSearch, std::wstring const &name, Dict_t const &dicRef, size_t cascadeRank=0)
A standard constructor using a pointer to a dictionary-object in memory.
~DictModule ()
DictModule (DictModule const &other)
copy constructor is blocked!!!
Dict_t const * getDict () const
returns a pointer to the connected dictionary.
void setDict (Dict_t const &dict)
connects the configuration to a certain dictionary.
void setDict (char const *dictFile)
Loads a dictionary from the hard disk and connects it to the configuration.
void setCaseMode (Global::CaseMode const &cm)
Specify how to handle upper/lower case queries.
Global::CaseMode getCaseMode () const
bool query (std::wstring const &query, iResultReceiver *answers)
Allows to query the iDctModule with some string.
Public Member Functions inherited from fsdict::DictSearch::AbstractDictModule
AbstractDictModule (DictSearch &myDictSearch, std::wstring const &name, size_t cascadeRank)
DictSearch & getMyDictSearch ()
size_t getDLevByWordlength (size_t wordLength) const
get the lev-distance threshold given a word length
Global::CaseMode getCaseMode () const
size_t getMaxNrOfPatterns () const
returns the current setting for the upper bound of applied variant patterns
size_t getDLevHypothetic () const
std::wstring const & getName () const
returns the DictModule's name
void setDLev (size_t dLev)
Sets a static Levenshtein distance threshold for approximate lookup.
void setDLevWordlengths (size_t wordlength_1, size_t wordlength_2, size_t wordlength_3)
configures the approximate lookup in a way that the lev-distance bound (see setDLev()) depends on the word length of the query word.
void setDLevWordlengths ()
Sets sensible standard values for word-length dependent distance bounds for approximate search.
void setMinNrOfPatterns (size_t min)
sets a new value for the upper bound of applied variant patterns
void setMaxNrOfPatterns (size_t max)
sets a new value for the upper bound of applied variant patterns
void setDLevHypothetic (size_t dlev)
sets a new value for the upper bound of applied variant patterns
Public Member Functions inherited from fsdict::DictSearch::iDictModule
iDictModule (size_t cascadeRank=0)
virtual ~iDictModule ()
A virtual destructor for a virtual class.
size_t getCascadeRank () const
void setPriority (int p)
Set a value in the range [0;100].
int getPriority () const
returns a value between 0 and 100 to indicate the DictModule's priority as compared to others This is used for a rough sorting order of all answers.
Detailed Description
An object of this type handles one dictionary that is to be used with DictSearch, and allows search with approximate search and approximate/hypothetic search.
Constructor & Destructor Documentation
fsdict::DictSearch::DictModule::DictModule (DictSearch & myDictSearch, std::wstring const & name, std::string const & dicFile, size_t cascadeRank = 0) inline
A standard constructor using a filepath pointing to a dictionary.
In this case, DictModule will load the dictionary and destroy it when the DictModule dies.
fsdict::DictSearch::DictModule::DictModule (DictSearch & myDictSearch, std::wstring const & name, Dict_t const & dicRef, size_t cascadeRank = 0) inline
A standard constructor using a pointer to a dictionary-object in memory.
Of course, in this case, DictModule will leave the dictionary-object alive when DictModule dies.
fsdict::DictSearch::DictModule::~DictModule () inline
fsdict::DictSearch::DictModule::DictModule (DictModule const & other)
copy constructor is blocked!!!
Member Function Documentation
Dict_t const* fsdict::DictSearch::DictModule::getDict () const inline
returns a pointer to the connected dictionary.
(May be 0)
Referenced by query(), and fsdict::TestDictSearch::testCascades().
void fsdict::DictSearch::DictModule::setDict (Dict_t const & dict) inline
connects the configuration to a certain dictionary.
   This dictionary will NOT be deleted in the destructor.
Parameters
dict a const reference to an existing dictionary.
Referenced by DictModule(), and setDict().
void fsdict::DictSearch::DictModule::setDict (char const * dictFile) inline
Loads a dictionary from the hard disk and connects it to the configuration.
   This dictionary will NOT be deleted in the destructor.
Parameters
dictFile a path to a file storing a dictionary of type Dict_t
void fsdict::DictSearch::DictModule::setCaseMode (Global::CaseMode const & cm) inline
Specify how to handle upper/lower case queries.
See Global::CaseMode to find out which options are available.
Note that all options belong to the namespace fsdict::Global.
Referenced by fsdict::DictSearch::readConfiguration(), and fsdict::TestDictSearch::testCaseMode().
Global::CaseMode fsdict::DictSearch::DictModule::getCaseMode () const inline
Referenced by query().
bool fsdict::DictSearch::DictModule::query (std::wstring const & query, iResultReceiver * answers) inline virtual
Allows to query the iDctModule with some string.
The iDictModule is expected to add all its answers/ interpretations to the CandidateSet that is passed.
Returns
true iff at least one answer was found
Implements fsdict::DictSearch::iDictModule.
The documentation for this class was generated from the following file:
fsdict/DictSearch/DictSearch.h