FSDict: fsdict::DictSearch::CandidateSet Class Reference
fsdict::DictSearch::CandidateSet Class Reference
CandidateSet is a simple container to collect candidates/interpretations from either a Vaam or a fsdict::MSMatch object.
#include <DictSearch.h>
Public Types
typedef
fsdict::DictSearch::Interpretation Interpretation_t
typedef std::vector
< Interpretation_t >::iterator iterator
typedef std::vector
< Interpretation_t >
::const_iterator const_iterator
Public Member Functions
void receive (const wchar_t *str, int levDistance, int annotation)
This is to fulfill the fsdict::LevFilter::CandidateReceiver interface.
void receive (fsdict::Interpretation const &vaam_interpretation)
This is to fulfill the fsdict::InterpretationReceiver interface.
void handleWordBoundaries (bool b)
void setCurrentDictModule (iDictModule const &dm)
void reset ()
alias for clear()
void clear ()
method defined as usual for containers, e.g.
iterator begin ()
method defined as usual for containers, e.g.
const_iterator begin () const
method defined as usual for containers, e.g.
iterator end ()
method defined as usual for containers, e.g.
const_iterator end () const
method defined as usual for containers, e.g.
size_t size () const
method defined as usual for containers, e.g.
bool empty () const
method defined as usual for containers, e.g.
Interpretation_t const & at (size_t i) const
method defined as usual for containers, e.g.
Detailed Description
CandidateSet is a simple container to collect candidates/interpretations from either a Vaam or a fsdict::MSMatch object.
Member Typedef Documentation
typedef fsdict::DictSearch::Interpretation fsdict::DictSearch::CandidateSet::Interpretation_t
typedef std::vector< Interpretation_t >::iterator fsdict::DictSearch::CandidateSet::iterator
typedef std::vector< Interpretation_t >::const_iterator fsdict::DictSearch::CandidateSet::const_iterator
Member Function Documentation
void fsdict::DictSearch::CandidateSet::receive (const wchar_t * str, int levDistance, int annotation) inline virtual
This is to fulfill the fsdict::LevFilter::CandidateReceiver interface.
Implements fsdict::LevFilter::CandidateReceiver.
void fsdict::DictSearch::CandidateSet::receive (fsdict::Interpretation const & vaam_interpretation) inline virtual
This is to fulfill the fsdict::InterpretationReceiver interface.
Implements fsdict::iInterpretationReceiver.
void fsdict::DictSearch::CandidateSet::handleWordBoundaries (bool b) inline virtual
Implements fsdict::DictSearch::iResultReceiver.
void fsdict::DictSearch::CandidateSet::setCurrentDictModule (iDictModule const & dm) inline virtual
See Also
currentDictModule_
Implements fsdict::DictSearch::iResultReceiver.
void fsdict::DictSearch::CandidateSet::reset () inline virtual
alias for clear()
See Also
clear()
Implements fsdict::LevFilter::CandidateReceiver.
void fsdict::DictSearch::CandidateSet::clear () inline
method defined as usual for containers, e.g.
in the std library
Referenced by main(), reset(), fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), and fsdict::TestDictSearch::testCaseMode().
iterator fsdict::DictSearch::CandidateSet::begin () inline
method defined as usual for containers, e.g.
in the std library
Referenced by main(), fsdict::TestDictSearch::smokeTest(), and fsdict::TestDictSearch::testCascades().
const_iterator fsdict::DictSearch::CandidateSet::begin () const inline
method defined as usual for containers, e.g.
in the std library
iterator fsdict::DictSearch::CandidateSet::end () inline
method defined as usual for containers, e.g.
in the std library
Referenced by main(), fsdict::TestDictSearch::smokeTest(), and fsdict::TestDictSearch::testCascades().
const_iterator fsdict::DictSearch::CandidateSet::end () const inline
method defined as usual for containers, e.g.
in the std library
size_t fsdict::DictSearch::CandidateSet::size () const inline
method defined as usual for containers, e.g.
in the std library
Referenced by fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), and fsdict::TestDictSearch::testCaseMode().
bool fsdict::DictSearch::CandidateSet::empty () const inline
method defined as usual for containers, e.g.
in the std library
Referenced by main().
Interpretation_t const& fsdict::DictSearch::CandidateSet::at (size_t i) const inline
method defined as usual for containers, e.g.
in the std library
Referenced by fsdict::TestDictSearch::smokeTest(), fsdict::TestDictSearch::testCascades(), and fsdict::TestDictSearch::testCaseMode().
The documentation for this class was generated from the following file:
fsdict/DictSearch/DictSearch.h