FSDict: fsdict::Getopt Class Reference
fsdict::Getopt Class Reference
A class for the parsing of command line arguments.
#include <Getopt.h>
Classes
class Exception
Public Types
enum ValueType { VOID, STRING }
enum Obligatority { OBLIGATORY, OPTIONAL }
Public Member Functions
Constructors
Getopt ()
A standard constructor.
Getopt (size_t argc, char const **argv)
This constructor also carries out the command line parsing.
Configure options
void specifyOption (std::string const &key, ValueType valueType, Obligatority obligatority=OPTIONAL)
specify an option.
void specifyOption (std::string const &key, ValueType valueType, std::string const &defaultValue)
Specify an option with a defaultValue.
void setOption (std::string const &key, std::string const &value)
Trigger Command line Parsing
void getOptions (size_t argc, char const **argv)
This option permits only options of the form option=value, and regular arguments.
void getOptionsAsSpecified (size_t argc, char const **argv)
Access options and arguments
typedef std::map< std::string,
ValueType >::const_iterator OptionIterator
void addArgument (std::string value)
const std::string & getProgName () const
bool hasOption (const std::string &key)
returns true iff an option with the specified key exists.
const std::string & getOption (const std::string &key)
returns the string value of the option with the specified key.
OptionIterator optionsBegin () const
OptionIterator optionsEnd () const
const std::string & getArgument (size_t idx) const
const size_t getArgumentCount () const
void print (std::wostream &os)
Detailed Description
A class for the parsing of command line arguments.
Member Typedef Documentation
typedef std::map< std::string, ValueType >::const_iterator fsdict::Getopt::OptionIterator
Member Enumeration Documentation
enum fsdict::Getopt::ValueType
Enumerator
VOID
STRING
enum fsdict::Getopt::Obligatority
Enumerator
OBLIGATORY
OPTIONAL
Constructor & Destructor Documentation
fsdict::Getopt::Getopt () inline
A standard constructor.
fsdict::Getopt::Getopt (size_t argc, char const ** argv) inline
This constructor also carries out the command line parsing.
No detailed specification of flags is possible here.
This is mainly for backwards compatibility.
Member Function Documentation
void fsdict::Getopt::specifyOption (std::string const & key, ValueType valueType, Obligatority obligatority = OPTIONAL) inline
specify an option.
Parameters
key the name of the key
valueType the valueType, one of VOID or STRING
obligatority one of OBLIGATORY or OPTIONAL
Referenced by main(), and fsdict::TestGetopt::testSpecified().
void fsdict::Getopt::specifyOption (std::string const & key, ValueType valueType, std::string const & defaultValue) inline
Specify an option with a defaultValue.
This obviously makes the option OPTIONAL: If it's not there ,the default valkue is used.
Parameters
key
valueType
defaultValue
void fsdict::Getopt::setOption (std::string const & key, std::string const & value) inline
void fsdict::Getopt::getOptions (size_t argc, char const ** argv) inline
This option permits only options of the form option=value, and regular arguments.
Referenced by fsdict::TestGetopt::testBasics(), and fsdict::TestGetopt::testFailure().
void fsdict::Getopt::getOptionsAsSpecified (size_t argc, char const ** argv) inline
Referenced by main(), and fsdict::TestGetopt::testSpecified().
void fsdict::Getopt::addArgument (std::string value) inline
Referenced by Getopt(), getOptions(), and getOptionsAsSpecified().
const std::string& fsdict::Getopt::getProgName () const inline
bool fsdict::Getopt::hasOption (const std::string & key) inline
returns true iff an option with the specified key exists.
Parameters
key
Returns
true iff an option with the specified key exists.
Referenced by getOption(), main(), fsdict::TestGetopt::testBasics(), and fsdict::TestGetopt::testSpecified().
const std::string& fsdict::Getopt::getOption (const std::string & key) inline
returns the string value of the option with the specified key.
Parameters
key
Returns
the string value of the option with the specified key.
Exceptions
a std::runtime_error if the specified key is not defined.
Referenced by main(), print(), fsdict::TestGetopt::testBasics(), and fsdict::TestGetopt::testSpecified().
OptionIterator fsdict::Getopt::optionsBegin () const inline
Referenced by print().
OptionIterator fsdict::Getopt::optionsEnd () const inline
Referenced by print().
const std::string& fsdict::Getopt::getArgument (size_t idx) const inline
Referenced by main(), fsdict::TestGetopt::testBasics(), and fsdict::TestGetopt::testSpecified().
const size_t fsdict::Getopt::getArgumentCount () const inline
Referenced by getArgument(), main(), fsdict::TestGetopt::testBasics(), and fsdict::TestGetopt::testSpecified().
void fsdict::Getopt::print (std::wostream & os) inline
The documentation for this class was generated from the following file:
fsdict/Getopt/Getopt.h