FSDict: fsdict::TempState< TransTable_t__ > Class Template Reference
fsdict::TempState< TransTable_t__ > Class Template Reference
TempState is to be used to construct a state of the automaton bit by bit.
#include <TempState.h>
Public Types
typedef std::vector
< Transition >::iterator TransIterator
typedef std::vector
< Transition >::const_iterator const_TransIterator
Public Member Functions
TransIterator transBegin ()
TransIterator transEnd ()
const_TransIterator transBegin () const
const_TransIterator transEnd () const
TempState ()
~TempState ()
InternalSize_t getPhValue () const
void addTransition (wchar_t label, InternalSize_t target, InternalSize_t targetPhNumber)
add an outgoing edge
void reset ()
reset the state for re-use
void setAnnotation (InternalSize_t annotation)
InternalSize_t getAnnotation () const
const wchar_t * getSusoString ()
void setFinal ()
mark the state as final
bool isFinal () const
returns true iff state is marked as final
Detailed Description
template<typename TransTable_t__>
class fsdict::TempState< TransTable_t__ >
TempState is to be used to construct a state of the automaton bit by bit.
Once it is certain that no more outgoing edges need to be added, it can be stored into the Automaton. Edges can point to already-stored edges only.
Author
Uli Reffle uli@r.nosp@m.effl.nosp@m.e.de
Date
2005
Member Typedef Documentation
template<typename TransTable_t__ > typedef std::vector< Transition >::iterator fsdict::TempState< TransTable_t__ >::TransIterator
template<typename TransTable_t__ > typedef std::vector< Transition >::const_iterator fsdict::TempState< TransTable_t__ >::const_TransIterator
Constructor & Destructor Documentation
template<typename TransTable_t__ > fsdict::TempState< TransTable_t__ >::TempState () inline
template<typename TransTable_t__ > fsdict::TempState< TransTable_t__ >::~TempState () inline
Member Function Documentation
template<typename TransTable_t__ > TransIterator fsdict::TempState< TransTable_t__ >::transBegin () inline
Referenced by fsdict::TempState< TransTable_t__ >::setFinal().
template<typename TransTable_t__ > TransIterator fsdict::TempState< TransTable_t__ >::transEnd () inline
Referenced by fsdict::TempState< TransTable_t__ >::setFinal().
template<typename TransTable_t__ > const_TransIterator fsdict::TempState< TransTable_t__ >::transBegin () const inline
template<typename TransTable_t__ > const_TransIterator fsdict::TempState< TransTable_t__ >::transEnd () const inline
template<typename TransTable_t__ > InternalSize_t fsdict::TempState< TransTable_t__ >::getPhValue () const inline
Referenced by fsdict::TempState< TransTable_t__ >::addTransition().
template<typename TransTable_t__ > void fsdict::TempState< TransTable_t__ >::addTransition (wchar_t label, InternalSize_t target, InternalSize_t targetPhNumber) inline
add an outgoing edge
Parameters
label
target
template<typename TransTable_t__ > void fsdict::TempState< TransTable_t__ >::reset () inline
reset the state for re-use
Referenced by fsdict::TempState< TransTable_t__ >::TempState().
template<typename TransTable_t__ > void fsdict::TempState< TransTable_t__ >::setAnnotation (InternalSize_t annotation) inline
template<typename TransTable_t__ > InternalSize_t fsdict::TempState< TransTable_t__ >::getAnnotation () const inline
Referenced by fsdict::TransTable< tttype, InternalCharType__, SizeType__ >::storeTempState().
template<typename TransTable_t__ > const wchar_t* fsdict::TempState< TransTable_t__ >::getSusoString () inline
Referenced by fsdict::TransTable< tttype, InternalCharType__, SizeType__ >::storeTempState().
template<typename TransTable_t__ > void fsdict::TempState< TransTable_t__ >::setFinal () inline
mark the state as final
template<typename TransTable_t__ > bool fsdict::TempState< TransTable_t__ >::isFinal () const inline
returns true iff state is marked as final
Returns
true iff state is marked as final
Referenced by fsdict::TransTable< tttype, InternalCharType__, SizeType__ >::compareStates(), fsdict::TempState< TransTable_t__ >::getPhValue(), and fsdict::TransTable< tttype, InternalCharType__, SizeType__ >::storeTempState().
The documentation for this class was generated from the following file:
fsdict/TransTable/TempState.h