FSDict: fsdict::INIConfig Class Reference
fsdict::INIConfig Class Reference
INIConfig is an object-oriented interface to the c-style "iniparser" to parse simple ini-style configuration files.
#include <INIConfig.h>
Classes
class SectionIterator
Iterates over all sections.
Public Member Functions
INIConfig ()
~INIConfig ()
INIConfig (std::string const &iniFile)
void load (std::string const &iniFile)
load a configuration file
void dump_ini (std::wostream &os) const
Dumps the current configuration as a loadable ini file.
bool hasKey (std::string const &key) const
Finds out if a given entry exists in the configuration.
char const * getstring (char const *key) const
throws a fsdictException if there is no such key
char const * getstring (std::string const &key) const
throws a fsdictException if there is no such key
int getint (char const *key) const
throws a fsdictException if there is no such key
int getint (std::string const &key) const
throws a fsdictException if there is no such key
double getdouble (char const *key) const
throws a fsdictException if there is no such key
double getdouble (std::string const &key) const
throws a fsdictException if there is no such key
bool getbool (std::string const &key) const
returns
SectionIterator sectionsBegin () const
SectionIterator sectionsEnd () const
Detailed Description
INIConfig is an object-oriented interface to the c-style "iniparser" to parse simple ini-style configuration files.
The parser supports a simple form of variable replacement. All keys that were defined in previous lines of the ini file can be accessed using the syntax ${someSection:someKey}. You can always access the directory containing the ini file with ${INIConfig:iniDir}
Author
Thorsten Vobl, Ulrich Reffle 2010, 2011
Constructor & Destructor Documentation
fsdict::INIConfig::INIConfig ()
fsdict::INIConfig::~INIConfig ()
fsdict::INIConfig::INIConfig (std::string const & iniFile)
Todo:
IMPORTANT clarify locale behaviour!!
Member Function Documentation
void fsdict::INIConfig::load (std::string const & iniFile)
load a configuration file
Referenced by INIConfig().
void fsdict::INIConfig::dump_ini (std::wostream & os) const
Dumps the current configuration as a loadable ini file.
Note that this method is not implemented in terms of its c counterpart. Because we want to dump to a c++ filehandle
bool fsdict::INIConfig::hasKey (std::string const & key) const
Finds out if a given entry exists in the configuration.
Referenced by fsdict::DictSearch::readConfiguration().
char const * fsdict::INIConfig::getstring (char const * key) const
throws a fsdictException if there is no such key
Referenced by getbool(), getdouble(), getint(), getstring(), fsdict::DictSearch::readConfiguration(), fsdict::TestINIConfig::testBasics(), and fsdict::TestINIConfig::testVariableSubstitution().
char const * fsdict::INIConfig::getstring (std::string const & key) const
throws a fsdictException if there is no such key
int fsdict::INIConfig::getint (char const * key) const
throws a fsdictException if there is no such key
Referenced by getbool(), getint(), fsdict::DictSearch::readConfiguration(), and fsdict::TestINIConfig::testBasics().
int fsdict::INIConfig::getint (std::string const & key) const
throws a fsdictException if there is no such key
double fsdict::INIConfig::getdouble (char const * key) const
throws a fsdictException if there is no such key
Referenced by getdouble(), and fsdict::TestINIConfig::testBasics().
double fsdict::INIConfig::getdouble (std::string const & key) const
throws a fsdictException if there is no such key
bool fsdict::INIConfig::getbool (std::string const & key) const
returns
true iff the value is a valid integer not equal to 0
true iff the value is the string "true"
false iff the value is the integer number 0
false iff the value is the string "false" Throws a fsdictException otherwise.
Referenced by fsdict::TestINIConfig::testBasics().
SectionIterator fsdict::INIConfig::sectionsBegin () const inline
Referenced by fsdict::DictSearch::readConfiguration(), and fsdict::TestINIConfig::testBasics().
SectionIterator fsdict::INIConfig::sectionsEnd () const inline
Referenced by fsdict::DictSearch::readConfiguration(), and fsdict::TestINIConfig::testBasics().
The documentation for this class was generated from the following files:
fsdict/INIConfig/INIConfig.h
fsdict/INIConfig/INIConfig.cxx