FSDict: fsdict::Val Class Reference
fsdict::Val Class Reference
#include <Val.h>
Public Types
typedef MinDic MinDic_t
typedef Vaam< MinDic_t >
::CandidateReceiver CandidateReceiver
Public Member Functions
Val (MinDic_t const &baseDic, const char *patternFile)
A trivial construtor, taking the input ressources as arguments.
Configuration
void setMinNrOfPatterns (size_t n)
restrict allowed number of pattern applications to greater or equal than n
void setMaxNrOfPatterns (size_t n)
restrict allowed number of pattern applications to less or equal than n
void setBaseDic (MinDic_t const &baseDic)
set the base dictionary.
void setCaseMode (Global::CaseMode caseMode)
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Usage/ Queries
bool query (std::wstring const &word, iInterpretationReceiver *interpretations) const
query a word to get possible interpretations as a variant.
Static Public Attributes
static const size_t INFINITE = (size_t)-1
Member Typedef Documentation
typedef MinDic fsdict::Val::MinDic_t
typedef Vaam< MinDic_t >::CandidateReceiver fsdict::Val::CandidateReceiver
Constructor & Destructor Documentation
fsdict::Val::Val (MinDic_t const & baseDic, const char * patternFile) inline
A trivial construtor, taking the input ressources as arguments.
Parameters
baseDic a reference to a MinDic_t that serves as baseDic
patternFile path to a file containing the spelling variant patterns (see class description for some more details).
Member Function Documentation
void fsdict::Val::setMinNrOfPatterns (size_t n) inline
restrict allowed number of pattern applications to greater or equal than n
Referenced by fsdict::DictSearch::DictModule::query(), and fsdict::TestVal::testBasics().
void fsdict::Val::setMaxNrOfPatterns (size_t n) inline
restrict allowed number of pattern applications to less or equal than n
Referenced by main(), fsdict::DictSearch::DictModule::query(), and fsdict::TestVal::testBasics().
void fsdict::Val::setBaseDic (MinDic_t const & baseDic) inline
set the base dictionary.
This restricts output words to words NOT present in this filterDic.
Referenced by fsdict::DictSearch::DictModule::query().
void fsdict::Val::setCaseMode (Global::CaseMode caseMode) inline
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Parameters
caseMode
Referenced by fsdict::DictSearch::DictModule::query().
bool fsdict::Val::query (std::wstring const & word, iInterpretationReceiver * interpretations) const inline
query a word to get possible interpretations as a variant.
You can write your own class that implements the interface iCandidateReceiver to receive all answers, but you can also use Vaam's subclass CandidateReceiver.
Referenced by fsdict::DictSearch::DictModule::query(), fsdict::TestVal::testBasics(), fsdict::TestVal::testPrint(), and fsdict::TestVal::testWordBorders().
Member Data Documentation
const size_t fsdict::Val::INFINITE = (size_t)-1 static
Referenced by fsdict::TestVal::testBasics().
The documentation for this class was generated from the following file:
fsdict/Val/Val.h