var namespacefsdict =
[
    [ "Global", "namespacefsdict_1_1Global.html", "namespacefsdict_1_1Global" ],
    [ "exceptions", "namespacefsdict_1_1exceptions.html", "namespacefsdict_1_1exceptions" ],
    [ "Alphabet", "classfsdict_1_1Alphabet.html", "classfsdict_1_1Alphabet" ],
    [ "UTF8_Codecvt", "classfsdict_1_1UTF8__Codecvt.html", "classfsdict_1_1UTF8__Codecvt" ],
    [ "CSLLocale", "classfsdict_1_1CSLLocale.html", "classfsdict_1_1CSLLocale" ],
    [ "TestCSLLocale", "classfsdict_1_1TestCSLLocale.html", "classfsdict_1_1TestCSLLocale" ],
    [ "DictSearch", "classfsdict_1_1DictSearch.html", "classfsdict_1_1DictSearch" ],
    [ "TestDictSearch", "classfsdict_1_1TestDictSearch.html", "classfsdict_1_1TestDictSearch" ],
    [ "FBDic", "classfsdict_1_1FBDic.html", "classfsdict_1_1FBDic" ],
    [ "TestFBDic", "classfsdict_1_1TestFBDic.html", "classfsdict_1_1TestFBDic" ],
    [ "FBDicString", "classfsdict_1_1FBDicString.html", "classfsdict_1_1FBDicString" ],
    [ "TestFBDicString", "classfsdict_1_1TestFBDicString.html", "classfsdict_1_1TestFBDicString" ],
    [ "Getopt", "classfsdict_1_1Getopt.html", "classfsdict_1_1Getopt" ],
    [ "TestGetopt", "classfsdict_1_1TestGetopt.html", "classfsdict_1_1TestGetopt" ],
    [ "Hash", "classfsdict_1_1Hash.html", "classfsdict_1_1Hash" ],
    [ "iDictionary", "classfsdict_1_1iDictionary.html", "classfsdict_1_1iDictionary" ],
    [ "INIConfig", "classfsdict_1_1INIConfig.html", "classfsdict_1_1INIConfig" ],
    [ "TestINIConfig", "classfsdict_1_1TestINIConfig.html", "classfsdict_1_1TestINIConfig" ],
    [ "table_cell", "structfsdict_1_1table__cell.html", "structfsdict_1_1table__cell" ],
    [ "LevDEA", "classfsdict_1_1LevDEA.html", "classfsdict_1_1LevDEA" ],
    [ "LevDistance", "classfsdict_1_1LevDistance.html", "classfsdict_1_1LevDistance" ],
    [ "TestLevDistance", "classfsdict_1_1TestLevDistance.html", "classfsdict_1_1TestLevDistance" ],
    [ "LevFilter", "classfsdict_1_1LevFilter.html", "classfsdict_1_1LevFilter" ],
    [ "TestCtype_OldGerman", "classfsdict_1_1TestCtype__OldGerman.html", "classfsdict_1_1TestCtype__OldGerman" ],
    [ "MinDic", "classfsdict_1_1MinDic.html", "classfsdict_1_1MinDic" ],
    [ "StateHash", "classfsdict_1_1StateHash.html", "classfsdict_1_1StateHash" ],
    [ "TestMinDic", "classfsdict_1_1TestMinDic.html", "classfsdict_1_1TestMinDic" ],
    [ "MinDic2", "classfsdict_1_1MinDic2.html", "classfsdict_1_1MinDic2" ],
    [ "MinDicString", "classfsdict_1_1MinDicString.html", "classfsdict_1_1MinDicString" ],
    [ "MSMatch", "classfsdict_1_1MSMatch.html", "classfsdict_1_1MSMatch" ],
    [ "ComputeInstruction", "classfsdict_1_1ComputeInstruction.html", "classfsdict_1_1ComputeInstruction" ],
    [ "Instruction", "classfsdict_1_1Instruction.html", "classfsdict_1_1Instruction" ],
    [ "Interpretation", "classfsdict_1_1Interpretation.html", "classfsdict_1_1Interpretation" ],
    [ "Pattern", "classfsdict_1_1Pattern.html", "classfsdict_1_1Pattern" ],
    [ "PatternGraph", "classfsdict_1_1PatternGraph.html", "classfsdict_1_1PatternGraph" ],
    [ "PatternSet", "classfsdict_1_1PatternSet.html", "classfsdict_1_1PatternSet" ],
    [ "PatternWeights", "classfsdict_1_1PatternWeights.html", "classfsdict_1_1PatternWeights" ],
    [ "PosPattern", "classfsdict_1_1PosPattern.html", "classfsdict_1_1PosPattern" ],
    [ "TestComputeInstruction", "classfsdict_1_1TestComputeInstruction.html", "classfsdict_1_1TestComputeInstruction" ],
    [ "TestPattern", "classfsdict_1_1TestPattern.html", "classfsdict_1_1TestPattern" ],
    [ "TestPatternWeights", "classfsdict_1_1TestPatternWeights.html", "classfsdict_1_1TestPatternWeights" ],
    [ "ResultSet", "classfsdict_1_1ResultSet.html", "classfsdict_1_1ResultSet" ],
    [ "Stopwatch", "classfsdict_1_1Stopwatch.html", "classfsdict_1_1Stopwatch" ],
    [ "Cell", "classfsdict_1_1Cell.html", null ],
    [ "Cell< TT_PERFHASH, InternalCharType__, SizeType__ >", "classfsdict_1_1Cell_3_01TT__PERFHASH_00_01InternalCharType_____00_01SizeType_____01_4.html", "classfsdict_1_1Cell_3_01TT__PERFHASH_00_01InternalCharType_____00_01SizeType_____01_4" ],
    [ "Cell< TT_STANDARD, InternalCharType__, SizeType__ >", "classfsdict_1_1Cell_3_01TT__STANDARD_00_01InternalCharType_____00_01SizeType_____01_4.html", "classfsdict_1_1Cell_3_01TT__STANDARD_00_01InternalCharType_____00_01SizeType_____01_4" ],
    [ "TempState", "classfsdict_1_1TempState.html", "classfsdict_1_1TempState" ],
    [ "TransTable", "classfsdict_1_1TransTable.html", "classfsdict_1_1TransTable" ],
    [ "TransTable< TT_PERFHASH, InternalCharType__, SizeType__ >", "classfsdict_1_1TransTable_3_01TT__PERFHASH_00_01InternalCharType_____00_01SizeType_____01_4.html", "classfsdict_1_1TransTable_3_01TT__PERFHASH_00_01InternalCharType_____00_01SizeType_____01_4" ],
    [ "TransTable< TT_STANDARD, InternalCharType__, SizeType__ >", "classfsdict_1_1TransTable_3_01TT__STANDARD_00_01InternalCharType_____00_01SizeType_____01_4.html", "classfsdict_1_1TransTable_3_01TT__STANDARD_00_01InternalCharType_____00_01SizeType_____01_4" ],
    [ "TestVaam", "classfsdict_1_1TestVaam.html", "classfsdict_1_1TestVaam" ],
    [ "iInterpretationReceiver", "classfsdict_1_1iInterpretationReceiver.html", "classfsdict_1_1iInterpretationReceiver" ],
    [ "Vaam", "classfsdict_1_1Vaam.html", "classfsdict_1_1Vaam" ],
    [ "TestVal", "classfsdict_1_1TestVal.html", "classfsdict_1_1TestVal" ],
    [ "Val", "classfsdict_1_1Val.html", "classfsdict_1_1Val" ]
];