FSDict: fsdict::ResultSet::Item Class Reference
fsdict::ResultSet::Item Class Reference
#include <ResultSet.h>
Public Member Functions
Item (const wchar_t *str, size_t levDistance, int ann)
Item (const Item &other)
copy constructor
bool operator== (const Item &other) const
Compares ONLY the string component.
void set (const wchar_t *str, size_t levDistance, int ann)
const wchar_t * getStr () const
int getAnn () const
int getLevDistance () const
Constructor & Destructor Documentation
fsdict::ResultSet::Item::Item (const wchar_t * str, size_t levDistance, int ann) [inline]
fsdict::ResultSet::Item::Item (const Item & other) [inline]
copy constructor
Member Function Documentation
bool fsdict::ResultSet::Item::operator== (const Item & other) const [inline]
Compares ONLY the string component.
void fsdict::ResultSet::Item::set (const wchar_t * str, size_t levDistance, int ann) [inline]
const wchar_t* fsdict::ResultSet::Item::getStr () const [inline]
Referenced by fsdict::ResultSet::cmp(), fsdict::ResultSet::is_equal(), and operator==().
int fsdict::ResultSet::Item::getAnn () const [inline]
int fsdict::ResultSet::Item::getLevDistance () const [inline]
The documentation for this class was generated from the following file:
fsdict/ResultSet/ResultSet.h