FSDict: fsdict::PatternSet Class Reference
fsdict::PatternSet Class Reference
A collection of patterns that should be available in some context.
#include <PatternSet.h>
Public Types
typedef PatternList_t::iterator iterator
typedef
PatternList_t::const_iterator const_iterator
Public Member Functions
PatternSet ()
Pattern const & at (size_t i) const
Returns a reference pointing to the i -th position of the set.
Pattern const & stripped_at (size_t i) const
Returns a reference pointing to the i -th position of the STRIPPED set.
iterator begin ()
returns an iterator at the first pattern of the list
iterator end ()
returns a classical past-the-end iterator
void push_back (Pattern const &pattern)
Adds a pattern to the PatternSet.
void loadPatterns (const char *patternFile)
Reads a set of patterns from file patternFile.
Protected Types
typedef std::vector< Pattern > PatternList_t
Protected Member Functions
const PatternList_t & patternList () const
Detailed Description
A collection of patterns that should be available in some context.
Author:
Ulrich Reffle, 2008
Member Typedef Documentation
typedef std::vector< Pattern > fsdict::PatternSet::PatternList_t [protected]
typedef PatternList_t::iterator fsdict::PatternSet::iterator
typedef PatternList_t::const_iterator fsdict::PatternSet::const_iterator
Constructor & Destructor Documentation
fsdict::PatternSet::PatternSet () [inline]
Member Function Documentation
Pattern const& fsdict::PatternSet::at (size_t i) const [inline]
Returns a reference pointing to the i -th position of the set.
Referenced by fsdict::PatternGraph::toDot().
Pattern const& fsdict::PatternSet::stripped_at (size_t i) const [inline]
Returns a reference pointing to the i -th position of the STRIPPED set.
iterator fsdict::PatternSet::begin () [inline]
returns an iterator at the first pattern of the list
Note that this is not the necessarily the first element of the internal container
Referenced by fsdict::PatternGraph::loadPatterns(), and fsdict::TestPattern::testPatternSet().
iterator fsdict::PatternSet::end () [inline]
returns a classical past-the-end iterator
Referenced by fsdict::TestPattern::testPatternSet().
void fsdict::PatternSet::push_back (Pattern const & pattern)
Adds a pattern to the PatternSet.
Referenced by loadPatterns(), and fsdict::populatePatternSet().
void fsdict::PatternSet::loadPatterns (const char * patternFile) [inline]
Reads a set of patterns from file patternFile.
The file is expected to contain one pattern per line, with a blank to separate left from right side. Example:
 t th
 ei ey
 u v
Reimplemented in fsdict::PatternGraph.
const PatternList_t& fsdict::PatternSet::patternList () const [inline, protected]
Referenced by fsdict::PatternGraph::loadPatterns().
The documentation for this class was generated from the following file:
fsdict/Pattern/PatternSet.h