FSDict: fsdict::TestLevDEA Class Reference
fsdict::TestLevDEA Class Reference
#include <TestLevDEA.h>
Public Member Functions
TestLevDEA ()
void run ()
void testWithInputString (std::string const msg, std::wstring const &str, bool valid, bool final=false, int distance=-1)
Utility function to conveniently test if a given input string leads to a valid/final state in the LevDEA.
void testBasics ()
void testSuffixMatch ()
Constructor & Destructor Documentation
fsdict::TestLevDEA::TestLevDEA ()
Member Function Documentation
void fsdict::TestLevDEA::run ()
void fsdict::TestLevDEA::testWithInputString (std::string const msg, std::wstring const & str, bool valid, bool final = false, int distance = -1) [inline]
Utility function to conveniently test if a given input string leads to a valid/final state in the LevDEA.
Referenced by testBasics(), and testSuffixMatch().
void fsdict::TestLevDEA::testBasics () [inline]
Referenced by run().
void fsdict::TestLevDEA::testSuffixMatch () [inline]
The documentation for this class was generated from the following file:
fsdict/LevDEA/Test/TestLevDEA.h