FSDict: fsdict::FBDic< AnnType > Class Template Reference
fsdict::FBDic< AnnType > Class Template Reference
Class FBDic ("Foward-Backward-Dictionary") covers a dictionary and its reversed variant in one object and also, more importantly, in one binary file on the hard disk.
#include <FBDic.h>
Classes
class DictEntry
During construction, used to represent one entry of the dictionary.
class Header
Public Types
typedef AnnType AnnType_t
typedef MinDic< AnnType_t > MinDic_t
Public Member Functions
Constructor
FBDic (const char *dicFile=0)
Access separate dictionaries
const MinDic_t & getFWDic () const
returns a reference to the forward dictionary
const MinDic_t & getBWDic () const
returns a reference to the backward dictionary
Compile a new dictionary
void compileDic (const char *txtFile)
compiles an FBDic from a .lex file.
void initConstruction ()
prepares the object for construction of a new FBDic Call before calling addToken() for the first time.
void addToken (std::wstring const &, AnnType_t)
Adds one new entry.
void finishConstruction ()
Finalize the construction Call after calling addToken() for the last time.
Load from /writing to hard disk
void loadFromFile (const char *binFile)
Load a compiled FBDic from hard disk.
void loadFromStream (FILE *fi)
Load a compiled FBDic from an open file stream.
void writeToFile (char const *binFile) const
dump FBDic automaton to a file in binary form.
void writeToStream (FILE *fo) const
dump FBDic automaton to an open file stream
Detailed Description
template<class AnnType = int>
class fsdict::FBDic< AnnType >
Class FBDic ("Foward-Backward-Dictionary") covers a dictionary and its reversed variant in one object and also, more importantly, in one binary file on the hard disk.
Author:
: Uli Reffle
Member Typedef Documentation
template<class AnnType = int> typedef AnnType fsdict::FBDic< AnnType >::AnnType_t
template<class AnnType = int> typedef MinDic< AnnType_t > fsdict::FBDic< AnnType >::MinDic_t
Constructor & Destructor Documentation
template<class AnnType = int> fsdict::FBDic< AnnType >::FBDic (const char * dicFile = 0) [explicit]
Member Function Documentation
template<class AnnType = int> const MinDic_t& fsdict::FBDic< AnnType >::getFWDic () const
returns a reference to the forward dictionary
Returns:
a reference to the forward dictionary
Referenced by main(), fsdict::TestFBDic::testBasics(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> const MinDic_t& fsdict::FBDic< AnnType >::getBWDic () const
returns a reference to the backward dictionary
Returns:
a reference to the backward dictionary
Referenced by fsdict::TestFBDic::testBasics(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> void fsdict::FBDic< AnnType >::compileDic (const char * txtFile)
compiles an FBDic from a .lex file.
Consult the FDic Manual for details on the format of the input file.
Reimplemented in fsdict::FBDicString.
Referenced by main().
template<class AnnType = int> void fsdict::FBDic< AnnType >::initConstruction ()
prepares the object for construction of a new FBDic Call before calling addToken() for the first time.
Reimplemented in fsdict::FBDicString.
Referenced by fsdict::TestFBDic::testBasics(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> void fsdict::FBDic< AnnType >::addToken (std::wstring const & , AnnType_t)
Adds one new entry.
Keys must be inserted in alphabetical order.
Referenced by fsdict::TestFBDic::testBasics(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> void fsdict::FBDic< AnnType >::finishConstruction ()
Finalize the construction Call after calling addToken() for the last time.
Reimplemented in fsdict::FBDicString.
Referenced by fsdict::TestFBDic::testBasics(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> void fsdict::FBDic< AnnType >::loadFromFile (const char * binFile) [inline]
Load a compiled FBDic from hard disk.
Parameters:
a file containing a compiled FBDic. (often: *.fbdic)
Reimplemented in fsdict::FBDicString.
Referenced by main().
template<class AnnType = int> void fsdict::FBDic< AnnType >::loadFromStream (FILE * fi) [inline]
Load a compiled FBDic from an open file stream.
Parameters:
fi a c-style file pointer.
Reimplemented in fsdict::FBDicString.
template<class AnnType = int> void fsdict::FBDic< AnnType >::writeToFile (char const * binFile) const [inline]
dump FBDic automaton to a file in binary form.
Parameters:
binFile File to write the automaton into.
Reimplemented in fsdict::FBDicString.
Referenced by main(), and fsdict::TestFBDic::testFileDump().
template<class AnnType = int> void fsdict::FBDic< AnnType >::writeToStream (FILE * fo) const [inline]
dump FBDic automaton to an open file stream
Parameters:
fo a c-style file pointer.
Reimplemented in fsdict::FBDicString.
The documentation for this class was generated from the following file:
fsdict/FBDic/FBDic.h