FSDict: fsdict::Stopwatch Class Reference
fsdict::Stopwatch Class Reference
#include <Stopwatch.h>
Public Member Functions
Stopwatch ()
void start ()
unsigned long long readSeconds () const
unsigned long long readMilliseconds () const
Constructor & Destructor Documentation
fsdict::Stopwatch::Stopwatch () [inline]
Member Function Documentation
void fsdict::Stopwatch::start () [inline]
Referenced by main(), and Stopwatch().
unsigned long long fsdict::Stopwatch::readSeconds () const [inline]
unsigned long long fsdict::Stopwatch::readMilliseconds () const [inline]
Referenced by main().
The documentation for this class was generated from the following file:
fsdict/Stopwatch.h