FSDict: fsdict::TestFBDic Class Reference
fsdict::TestFBDic Class Reference
#include <TestFBDic.h>
Public Member Functions
TestFBDic ()
void run ()
void testBasics ()
test the basic methods for reading access like getRoot, walk, isFinal etc.
void testFileDump ()
Constructor & Destructor Documentation
fsdict::TestFBDic::TestFBDic ()
Member Function Documentation
void fsdict::TestFBDic::run ()
Referenced by main().
void fsdict::TestFBDic::testBasics ()
test the basic methods for reading access like getRoot, walk, isFinal etc.
Referenced by run().
void fsdict::TestFBDic::testFileDump ()
Referenced by run().
The documentation for this class was generated from the following file:
fsdict/FBDic/Test/TestFBDic.h