FSDict: fsdict::FBDicString Class Reference
fsdict::FBDicString Class Reference
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
#include <FBDicString.h>
Classes
class Header
Public Types
typedef FBDic FBDic_t
Public Member Functions
FBDicString ()
FBDicString (char const *dicFile)
Create a FBDicString object and load a dic from the specified file.
void setKeyValueDelimiter (uchar c)
uchar const * lookup (wchar_t *key) const
uchar const * getAnnByPerfHashValue_FW (size_t perfHashValue) const
return the string value annotated to the entry with the given perfect hash value in the FW dic
uchar const * getAnnByPerfHashValue_BW (size_t perfHashValue) const
return the string value annotated to the entry with the given perfect hash value in the BW dic
uchar const * getAnnByOffset (size_t offset) const
return the string value at the specified offset in the annotation buffer
void loadFromFile (char const *dicFile)
Load a compiled FBDic from hard disk.
void loadFromStream (FILE *fi)
Load a compiled FBDic from an open file stream.
void writeToFile (char const *dicFile) const
dump FBDic automaton to a file in binary form.
void writeToStream (FILE *fo) const
dump FBDic automaton to an open file stream
void initConstruction ()
prepares the object for construction of a new FBDic Call before calling addToken() for the first time.
void finishConstruction ()
Finalize the construction Call after calling addToken() for the last time.
void compileDic (const char *lexFile)
compiles an FBDic from a .lex file.
void doAnalysis () const
Detailed Description
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
Currently the keys of the dictionaries are represented as wide strings, while the annotations are stored as utf-8 sequences. This makes the data structure smaller, and in some contexts also faster. But, now that the whole rest of the library has been changed to wide strings, this is definitely a bit out-dated.
Todo:
Change to consistent use of wstring
Author:
Uli Reffle
Date:
2006-2010
Member Typedef Documentation
typedef FBDic fsdict::FBDicString::FBDic_t
Constructor & Destructor Documentation
fsdict::FBDicString::FBDicString () [inline]
fsdict::FBDicString::FBDicString (char const * dicFile) [inline]
Create a FBDicString object and load a dic from the specified file.
Member Function Documentation
void fsdict::FBDicString::setKeyValueDelimiter (uchar c) [inline]
Referenced by main().
uchar const* fsdict::FBDicString::lookup (wchar_t * key) const [inline]
uchar const* fsdict::FBDicString::getAnnByPerfHashValue_FW (size_t perfHashValue) const [inline]
return the string value annotated to the entry with the given perfect hash value in the FW dic
uchar const* fsdict::FBDicString::getAnnByPerfHashValue_BW (size_t perfHashValue) const [inline]
return the string value annotated to the entry with the given perfect hash value in the BW dic
uchar const* fsdict::FBDicString::getAnnByOffset (size_t offset) const [inline]
return the string value at the specified offset in the annotation buffer
void fsdict::FBDicString::loadFromFile (char const * binFile) [inline]
Load a compiled FBDic from hard disk.
Parameters:
a file containing a compiled FBDic. (often: *.fbdic)
Reimplemented from fsdict::FBDic<>.
void fsdict::FBDicString::loadFromStream (FILE * fi) [inline]
Load a compiled FBDic from an open file stream.
Parameters:
fi a c-style file pointer.
Reimplemented from fsdict::FBDic<>.
void fsdict::FBDicString::writeToFile (char const * binFile) const [inline]
dump FBDic automaton to a file in binary form.
Parameters:
binFile File to write the automaton into.
Reimplemented from fsdict::FBDic<>.
Referenced by main().
void fsdict::FBDicString::writeToStream (FILE * fo) const [inline]
dump FBDic automaton to an open file stream
Parameters:
fo a c-style file pointer.
Reimplemented from fsdict::FBDic<>.
void fsdict::FBDicString::initConstruction () [inline]
prepares the object for construction of a new FBDic Call before calling addToken() for the first time.
Reimplemented from fsdict::FBDic<>.
void fsdict::FBDicString::finishConstruction () [inline]
Finalize the construction Call after calling addToken() for the last time.
Reimplemented from fsdict::FBDic<>.
void fsdict::FBDicString::compileDic (const char * txtFile) [inline]
compiles an FBDic from a .lex file.
Consult the FDic Manual for details on the format of the input file.
Reimplemented from fsdict::FBDic<>.
Referenced by main().
void fsdict::FBDicString::doAnalysis () const [inline]
The documentation for this class was generated from the following file:
fsdict/FBDicString/FBDicString.h