FSDict: fsdict::PatternGraph::Alphabet Class Reference
fsdict::PatternGraph::Alphabet Class Reference
#include <PatternGraph.h>
Public Member Functions
void initConstruction ()
void addChar (wchar_t c)
void finishConstruction ()
wchar_t encode (wchar_t c) const
wchar_t decode (wchar_t c) const
size_t size () const
Member Function Documentation
void fsdict::PatternGraph::Alphabet::initConstruction () [inline]
Referenced by fsdict::PatternGraph::loadPatterns().
void fsdict::PatternGraph::Alphabet::addChar (wchar_t c) [inline]
Referenced by fsdict::PatternGraph::loadPatterns().
void fsdict::PatternGraph::Alphabet::finishConstruction () [inline]
Referenced by fsdict::PatternGraph::loadPatterns().
wchar_t fsdict::PatternGraph::Alphabet::encode (wchar_t c) const [inline]
wchar_t fsdict::PatternGraph::Alphabet::decode (wchar_t c) const [inline]
size_t fsdict::PatternGraph::Alphabet::size () const [inline]
The documentation for this class was generated from the following file:
fsdict/Pattern/PatternGraph.h