FSDict: fsdict::LevDEA::Pos Class Reference
fsdict::LevDEA::Pos Class Reference
External representation of a state of the Levenshtein Automaton.
#include <LevDEA.h>
Public Member Functions
Pos (int position=0, size_t patternPos=0)
Constructor, optional values for position and patternPos.
int position () const
Returns the position in the Lev.
size_t patternPos () const
Returns the position in the pattern.
void set (int position, size_t patternPos)
Set new values for positions in the automaton and the pattern.
bool isValid () const
Returns true iff the current state is a valid one, returns false iff it is a fail state (or: trap state).
Detailed Description
External representation of a state of the Levenshtein Automaton.
Constructor & Destructor Documentation
fsdict::LevDEA::Pos::Pos (int position = 0, size_t patternPos = 0) [inline]
Constructor, optional values for position and patternPos.
Member Function Documentation
int fsdict::LevDEA::Pos::position () const [inline]
Returns the position in the Lev.
automaton.
Referenced by fsdict::LevDEA::getDistance(), fsdict::LevDEA::startSuffixMatch(), fsdict::TestLevDEA::testSuffixMatch(), and fsdict::LevDEA::walk().
size_t fsdict::LevDEA::Pos::patternPos () const [inline]
Returns the position in the pattern.
Referenced by fsdict::LevDEA::getDistance(), fsdict::LevDEA::startSuffixMatch(), and fsdict::LevDEA::walk().
void fsdict::LevDEA::Pos::set (int position, size_t patternPos) [inline]
Set new values for positions in the automaton and the pattern.
bool fsdict::LevDEA::Pos::isValid () const [inline]
Returns true iff the current state is a valid one, returns false iff it is a fail state (or: trap state).
Referenced by fsdict::LevDEA::getDistance(), and fsdict::LevDEA::walkStr().
The documentation for this class was generated from the following file:
fsdict/LevDEA/LevDEA.h