FSDict: fsdict::LevDEA Class Reference
fsdict::LevDEA Class Reference
LevDEA gives access to deterministic levenshtein automata.
#include <LevDEA.h>
Classes
class Pos
External representation of a state of the Levenshtein Automaton.
Public Member Functions
LevDEA (int init_k=0)
A regular constructor.
~LevDEA ()
A regular destructor.
Pos getRoot () const
Returns the root state (at the root of the automaton, and the start of the pattern.
Pos walk (const Pos &p, wchar_t c) const
Follow a transition in the automaton.
Pos walkStr (const Pos &p, const std::wstring &str) const
do a walk sequentially for a std::wstring.
Pos walkStr (const Pos &p, const wchar_t *str) const
do a walk sequentially for a c-string
bool isFinal (const Pos &p) const
Returns true iff state p is a position standing for a final state.
int getDistance (const Pos &p) const
Returns the lev.
bool startSuffixMatch (const Pos &p, std::vector< size_t > *patternStartPositions)
const std::wstring & getPattern ()
Returns the current search pattern.
void setThreshold (size_t k)
Set a max Levenshtein distance for matching.
size_t getThreshold () const
void loadPattern (const wchar_t *p)
Load a new search pattern.
void loadPattern_utf8 (const char *p)
Load a new search pattern, pass a utf8-encoded single-byte string.
void printTable () const
void printCharvec () const
void printBits (const bits64 &) const
Detailed Description
LevDEA gives access to deterministic levenshtein automata.
It is an implementation of the concepts described in "S. Mihov and K. Schulz. Fast approximate search in large dictionaries. Computational Linguistics, 30, 2004."
This class is one huge memory leak!!!
Author:
Ulrich Reffle
Date:
2006
Constructor & Destructor Documentation
fsdict::LevDEA::LevDEA (int init_k = 0)
A regular constructor.
fsdict::LevDEA::~LevDEA ()
A regular destructor.
Member Function Documentation
Pos fsdict::LevDEA::getRoot () const [inline]
Returns the root state (at the root of the automaton, and the start of the pattern.
)
Referenced by fsdict::TestLevDEA::testSuffixMatch(), and fsdict::TestLevDEA::testWithInputString().
LevDEA::Pos fsdict::LevDEA::walk (const Pos & p, wchar_t c) const [inline]
Follow a transition in the automaton.
Input-char c is translated into a bit-vector which then is used as "input symbol" for the automaton.
Parameters:
p a start position in the automaton
c a character
Returns:
the new position
Referenced by walkStr().
LevDEA::Pos fsdict::LevDEA::walkStr (const Pos & p, const std::wstring & str) const [inline]
do a walk sequentially for a std::wstring.
Parameters:
p a start position in the automaton
str a const reference to a std::wstring
Returns:
the new position
Referenced by fsdict::TestLevDEA::testSuffixMatch(), and fsdict::TestLevDEA::testWithInputString().
LevDEA::Pos fsdict::LevDEA::walkStr (const Pos & p, const wchar_t * str) const [inline]
do a walk sequentially for a c-string
Parameters:
p a start position in the automaton
str a c-string
Returns:
the new position
bool fsdict::LevDEA::isFinal (const Pos & p) const [inline]
Returns true iff state p is a position standing for a final state.
Parameters:
p a position in the automaton
Returns:
true iff state p is a position standing for a final state
Referenced by fsdict::TestLevDEA::testWithInputString().
int fsdict::LevDEA::getDistance (const Pos & p) const [inline]
Returns the lev.
distance for a match at that position.
Referenced by isFinal(), and fsdict::TestLevDEA::testWithInputString().
bool fsdict::LevDEA::startSuffixMatch (const Pos & p, std::vector< size_t > * patternStartPositions) [inline]
Referenced by fsdict::TestLevDEA::testSuffixMatch().
const std::wstring& fsdict::LevDEA::getPattern () [inline]
Returns the current search pattern.
Referenced by fsdict::TestLevDEA::testWithInputString().
void fsdict::LevDEA::setThreshold (size_t k)
Set a max Levenshtein distance for matching.
Referenced by LevDEA(), fsdict::TestLevDEA::testBasics(), and fsdict::TestLevDEA::testSuffixMatch().
size_t fsdict::LevDEA::getThreshold () const
Referenced by fsdict::TestLevDEA::testWithInputString().
void fsdict::LevDEA::loadPattern (const wchar_t * p)
Load a new search pattern.
Referenced by loadPattern_utf8(), fsdict::TestLevDEA::testBasics(), and fsdict::TestLevDEA::testSuffixMatch().
void fsdict::LevDEA::loadPattern_utf8 (const char * p)
Load a new search pattern, pass a utf8-encoded single-byte string.
void fsdict::LevDEA::printTable () const
void fsdict::LevDEA::printCharvec () const
void fsdict::LevDEA::printBits (const bits64 & n) const
Referenced by printCharvec().
The documentation for this class was generated from the following files:
fsdict/LevDEA/LevDEA.h
fsdict/LevDEA/LevDEA.cxx