FSDict: fsdict::Hash< charType_t__ > Class Template Reference
fsdict::Hash< charType_t__ > Class Template Reference
Hash provides a hash table which stores and finds c-strings.
#include <Hash.h>
Public Types
typedef charType_t__ charType_t
Public Member Functions
Hash (size_t estimatedNrOfKeys, charType_t *&keyBuffer, size_t &lengthOfKeyBuffer)
constructor
size_t findOrInsert (const charType_t *key)
insert a key into the hash table
size_t find (const charType_t *key) const
look up a key in the hash table
void reset ()
size_t getTableSize () const
size_t getLengthOfKeyStrings () const
template<>
size_t getHashCode (const charType_t *str) const
template<>
size_t getHashCode (const charType_t *str) const
template<>
int strcmpTemplate (const charType_t *w1, const charType_t *w2) const
template<>
wchar_t * strncpyTemplate (charType_t *w1, const charType_t *w2, size_t n) const
template<>
size_t strlenTemplate (const charType_t *w) const
template<>
int strcmpTemplate (const charType_t *w1, const charType_t *w2) const
template<>
uchar * strncpyTemplate (charType_t *w1, const charType_t *w2, size_t n) const
template<>
size_t strlenTemplate (const charType_t *w) const
Detailed Description
template<class charType_t__>
class fsdict::Hash< charType_t__ >
Hash provides a hash table which stores and finds c-strings.
The class is designed to be used for hashing suso-strings for fast traversable dictionaries -
Inserted strings are stored in a buffer here in Hash, the hash table stores pointers into that buffer.
Author:
Uli Reffle, <uli@reffle.de>
Member Typedef Documentation
template<class charType_t__> typedef charType_t__ fsdict::Hash< charType_t__ >::charType_t
Constructor & Destructor Documentation
template<class charType_t > fsdict::Hash< charType_t >::Hash (size_t estimatedNrOfKeys, charType_t *& keyBuffer, size_t & lengthOfKeyBuffer) [inline]
constructor
Parameters:
in/out] keyBuffer a reference to a c-string, where the keys are stored.
[in] estimatedNrOfKeys an estimation that helps to choose the right size of the hashtable
in/out] lengthOfKeyBuffer
Todo:
think about the heuristics concerning the buffer initialization size
Member Function Documentation
template<class charType_t > size_t fsdict::Hash< charType_t >::findOrInsert (const charType_t * key) [inline]
insert a key into the hash table
Parameters:
key
Referenced by smokeTest().
template<class charType_t > size_t fsdict::Hash< charType_t >::find (const charType_t * key) const [inline]
look up a key in the hash table
Parameters:
key
Returns:
a value >0 iff the key was found, 0 otherwise
Referenced by smokeTest().
template<class charType_t > void fsdict::Hash< charType_t >::reset () [inline]
template<class charType_t > size_t fsdict::Hash< charType_t >::getTableSize () const [inline]
Referenced by fsdict::Hash< charType_t__ >::find(), fsdict::Hash< charType_t__ >::findOrInsert(), and fsdict::Hash< charType_t__ >::getHashCode().
template<class charType_t > size_t fsdict::Hash< charType_t >::getLengthOfKeyStrings () const [inline]
template<> size_t fsdict::Hash< uchar >::getHashCode (const charType_t * str) const [inline]
Todo:
FIND A GOOD NUMBER FOR THE HASHING !!!
template<> size_t fsdict::Hash< wchar_t >::getHashCode (const charType_t * str) const [inline]
template<> int fsdict::Hash< wchar_t >::strcmpTemplate (const charType_t * w1, const charType_t * w2) const [inline]
template<> wchar_t * fsdict::Hash< wchar_t >::strncpyTemplate (charType_t * w1, const charType_t * w2, size_t n) const [inline]
template<> size_t fsdict::Hash< wchar_t >::strlenTemplate (const charType_t * w) const [inline]
template<> int fsdict::Hash< uchar >::strcmpTemplate (const charType_t * w1, const charType_t * w2) const [inline]
template<> uchar * fsdict::Hash< uchar >::strncpyTemplate (charType_t * w1, const charType_t * w2, size_t n) const [inline]
template<> size_t fsdict::Hash< uchar >::strlenTemplate (const charType_t * w) const [inline]
The documentation for this class was generated from the following file:
fsdict/Hash/Hash.h