FSDict: fsdict::MinDic< AnnType > Class Template Reference
fsdict::MinDic< AnnType > Class Template Reference
class MinDic performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
#include <MinDic.h>
Classes
class Header
class State
This class provides a much easier interface to the MinDic if the guts of the automaton have to be explored state- and transition-wise.
class TokenIterator
This iterator allows to traverse through all words of the language the MinDic describes.
Public Types
typedef TransTable
< TT_PERFHASH, uint16_t > TransTable_t
typedef AnnType AnnType_t
The datatype of the annotation that comes with each dictionary entry.
Public Member Functions
MinDic (const char *dicFile=0)
Create a new MinDic.
MinDic (MinDic< AnnType_t > const &other)
The copy constructor is NOT IMPLEMENTED at the moment.
Lookup
bool lookup (const wchar_t *key, AnnType_t *annotation=0) const
Use this function to do a convenient lookup.
bool lookup (std::wstring const &key, AnnType_t *annotation=0) const
bool hasPrefix (std::wstring const &prefix) const
bool getAnnotation (const wchar_t *key, AnnType_t *annotation) const
this method is renamed to lookup()
const AnnType_t & getAnnotation (size_t perfHashValue) const
State getRootState () const
Get a State object of the automaton's root/ start state.
TokenIterator tokensBegin () const
TokenIterator tokensEnd () const
Loading from /writing to hard disk
void loadFromFile (const char *binFile)
Load a compiled MinDic from hard disk.
void loadFromStream (FILE *fi)
Load a compiled MinDic from an open file stream.
void writeToFile (char const *binFile) const
dump MinDic automaton to a file in binary form.
void writeToStream (FILE *fo) const
dump MinDic automaton to an open file stream
Construction of a new MinDic
void compileDic (const char *txtFile)
The funtion that actually executes the computation of the trie.
void setKeyValueDelimiter (wchar_t delimiter)
Set the key-value delimiter to be used during the parsing of txt input files.
void parseAnnotation (std::wstring *str, AnnType_t *annotation) const
This method parses an input line (provided as param str).
void initConstruction ()
prepares the object for construction of a new MinDic.
void addToken (const wchar_t *input, const AnnType_t &value)
Add one new entry.
void finishConstruction ()
Finalize the construction Call after calling addToken() for the last time.
Convenience, Information, Debug
void printDic () const
void printDic (StateId_t initState) const
extracts the trie to stdout
size_t getNrOfKeys () const
void doAnalysis () const
int getFirstAnn (StateId_t state)
This method from TransTable is blocked for MinDic, not implemented here!
Protected Member Functions
const AnnType_t & annotationsAt (size_t n) const
Detailed Description
template<class AnnType = int>
class fsdict::MinDic< AnnType >
class MinDic performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
It follows an algorithm described in Jan Daciuk et. al., Incremental Construction of Minimal Acyclic Finite-State Automata, 2000.
Many ideas for the implementation are adapted from a C-program written by Stoyan Mihov.
Note that a MinDic inherits from TransTable and so offers all of TransTable's interface to the guts of the automaton. However this might change in the future.
Author:
Ulrich Reffle, <uli@cis.uni-muenchen.de>
Date:
Apr 2006
Member Typedef Documentation
template<class AnnType = int> typedef TransTable< TT_PERFHASH, uint16_t > fsdict::MinDic< AnnType >::TransTable_t
template<class AnnType = int> typedef AnnType fsdict::MinDic< AnnType >::AnnType_t
The datatype of the annotation that comes with each dictionary entry.
Note that AnnType_t, currently, has to be a trivial datatype: if you store an object x of type AnnType_t, the MinDic will store exactly sizeof(AnnType_t) bytes, beginning at address &x. Heap data will be lost.
Constructor & Destructor Documentation
template<class AnnType = int> fsdict::MinDic< AnnType >::MinDic (const char * dicFile = 0)
Create a new MinDic.
An optional file-path as argument invokes a call to loadFromFile.
Parameters:
a file containing a compiled MinDic. (optional; often: *.mdic)
template<class AnnType = int> fsdict::MinDic< AnnType >::MinDic (MinDic< AnnType_t > const & other)
The copy constructor is NOT IMPLEMENTED at the moment.
Member Function Documentation
template<class AnnType = int> bool fsdict::MinDic< AnnType >::lookup (const wchar_t * key, AnnType_t * annotation = 0) const [inline, virtual]
Use this function to do a convenient lookup.
If you don't need the annotation, just pass on a NULL-Pointer or omit the 2nd argument.
Parameters:
[in] key a key of the dictionary
[out] annotation a pointer where to store the found annotation. If NULL, then annotation is discarded
Returns:
true iff key was found in the dictionary
Implements fsdict::iDictionary< AnnType >.
Referenced by main().
template<class AnnType = int> bool fsdict::MinDic< AnnType >::lookup (std::wstring const & key, AnnType_t * annotation = 0) const [inline, virtual]
Implements fsdict::iDictionary< AnnType >.
template<class AnnType = int> bool fsdict::MinDic< AnnType >::hasPrefix (std::wstring const & prefix) const [inline]
template<class AnnType = int> bool fsdict::MinDic< AnnType >::getAnnotation (const wchar_t * key, AnnType_t * annotation) const [inline]
this method is renamed to lookup()
template<class AnnType = int> const AnnType_t& fsdict::MinDic< AnnType >::getAnnotation (size_t perfHashValue) const [inline]
template<class AnnType = int> State fsdict::MinDic< AnnType >::getRootState () const [inline]
Get a State object of the automaton's root/ start state.
Returns:
a State object of the automaton's root/ start state.
See also:
State
template<class AnnType = int> TokenIterator fsdict::MinDic< AnnType >::tokensBegin () const [inline]
template<class AnnType = int> TokenIterator fsdict::MinDic< AnnType >::tokensEnd () const [inline]
template<class AnnType = int> void fsdict::MinDic< AnnType >::loadFromFile (const char * binFile) [inline]
Load a compiled MinDic from hard disk.
Parameters:
a file containing a compiled MinDic. (often: *.mdic)
Reimplemented in fsdict::MinDicString.
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::loadFromStream (FILE * fi) [inline]
Load a compiled MinDic from an open file stream.
Parameters:
fi a c-style file pointer.
Reimplemented in fsdict::MinDicString.
template<class AnnType = int> void fsdict::MinDic< AnnType >::writeToFile (char const * binFile) const [inline]
dump MinDic automaton to a file in binary form.
Parameters:
binFile File to write the automaton into.
Reimplemented in fsdict::MinDicString.
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::writeToStream (FILE * fo) const [inline]
dump MinDic automaton to an open file stream
Parameters:
fo a c-style file pointer.
Reimplemented in fsdict::MinDicString.
template<class AnnType = int> void fsdict::MinDic< AnnType >::compileDic (const char * txtFile) [inline]
The funtion that actually executes the computation of the trie.
Todo:
Should this method be public??? Maybe not ...
Parameters:
txtFile The dictionary (including annotations) in txt format
Reimplemented in fsdict::MinDicString.
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::setKeyValueDelimiter (wchar_t delimiter) [inline]
Set the key-value delimiter to be used during the parsing of txt input files.
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::parseAnnotation (std::wstring * str, AnnType_t * annotation) const [inline]
This method parses an input line (provided as param str).
If str has an annotation attached to the key, this annotation is clipped from str and stored in the param annotation
Parameters:
in/out] str
[out] annotation
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::initConstruction () [inline]
prepares the object for construction of a new MinDic.
Call before calling addToken() for the first time.
Reimplemented in fsdict::MinDicString.
Referenced by main(), fsdict::TestMinDic::TestMinDic(), fsdict::TestVal::testPrint(), fsdict::TestVal::testWordBorders(), and fsdict::TestVaam::testWordBorders().
template<class AnnType = int> void fsdict::MinDic< AnnType >::addToken (const wchar_t * input, const AnnType_t & value) [inline]
Add one new entry.
Keys must be inserted in alphabetical order.
Referenced by main(), fsdict::TestMinDic::TestMinDic(), fsdict::TestVal::testPrint(), fsdict::TestVal::testWordBorders(), and fsdict::TestVaam::testWordBorders().
template<class AnnType = int> void fsdict::MinDic< AnnType >::finishConstruction () [inline]
Finalize the construction Call after calling addToken() for the last time.
Reimplemented in fsdict::MinDicString.
Referenced by main(), fsdict::TestMinDic::TestMinDic(), fsdict::TestVal::testPrint(), fsdict::TestVal::testWordBorders(), and fsdict::TestVaam::testWordBorders().
template<class AnnType = int> void fsdict::MinDic< AnnType >::printDic () const [inline]
Reimplemented in fsdict::MinDicString.
Referenced by main().
template<class AnnType = int> void fsdict::MinDic< AnnType >::printDic (StateId_t initState) const [inline]
extracts the trie to stdout
template<class AnnType = int> size_t fsdict::MinDic< AnnType >::getNrOfKeys () const [inline]
template<class AnnType = int> void fsdict::MinDic< AnnType >::doAnalysis () const [inline]
Reimplemented in fsdict::MinDicString.
Referenced by main().
template<class AnnType = int> int fsdict::MinDic< AnnType >::getFirstAnn (StateId_t state) [inline]
This method from TransTable is blocked for MinDic, not implemented here!
template<class AnnType = int> const AnnType_t& fsdict::MinDic< AnnType >::annotationsAt (size_t n) const [inline, protected]
The documentation for this class was generated from the following file:
fsdict/MinDic/MinDic.h