FSDict: fsdict::TestINIConfig Class Reference
fsdict::TestINIConfig Class Reference
#include <TestINIConfig.h>
Public Member Functions
TestINIConfig ()
void run ()
void testBasics ()
test the basic methods
void testLongLine ()
void testVariableSubstitution ()
Constructor & Destructor Documentation
fsdict::TestINIConfig::TestINIConfig ()
Member Function Documentation
void fsdict::TestINIConfig::run ()
Referenced by main().
void fsdict::TestINIConfig::testBasics ()
test the basic methods
Referenced by run().
void fsdict::TestINIConfig::testLongLine ()
Referenced by run().
void fsdict::TestINIConfig::testVariableSubstitution ()
Referenced by run().
The documentation for this class was generated from the following file:
fsdict/INIConfig/Test/TestINIConfig.h