FSDict: fsdict::Instruction Class Reference
fsdict::Instruction Class Reference
Instruction is a std::vector< PosPattern>, and it's an instruction in the sense we use the word in connection with spelling variants.
#include <Instruction.h>
Public Member Functions
Constructors/ Destructor / Operators
Instruction ()
standard constructor
bool operator== (Instruction const &other) const
Equality of instructions is quite obvious: two instructions are equal if both have the same size and all PosPatterns are equal.
Serialization
void setDestroyed (bool b=true)
sets the status of the trace
bool isDestroyed () const
returns true iff the status of the trace is set to DESTROYED
void print (std::wostream &os=std::wcout) const
prints a string-representation of the instruction to stdout or to another std::wstream specified as argument.
std::wstring toString () const
size_t parseFromString (std::wstring const &str, size_t offset=0)
Converts a string as produced by toString() back into the data structure.
Usage of the trace
void applyTo (std::wstring *str, int direction=1) const
apply the instruction to the string passed as pointer argument
bool containsPattern (Pattern const &pat) const
return true if the Instruction contains the given pattern.
Detailed Description
Instruction is a std::vector< PosPattern>, and it's an instruction in the sense we use the word in connection with spelling variants.
Constructor & Destructor Documentation
fsdict::Instruction::Instruction ()
standard constructor
Member Function Documentation
bool fsdict::Instruction::operator== (Instruction const & other) const
Equality of instructions is quite obvious: two instructions are equal if both have the same size and all PosPatterns are equal.
void fsdict::Instruction::setDestroyed (bool b = true)
sets the status of the trace
bool fsdict::Instruction::isDestroyed () const
returns true iff the status of the trace is set to DESTROYED
void fsdict::Instruction::print (std::wostream & os = std::wcout) const
prints a string-representation of the instruction to stdout or to another std::wstream specified as argument.
Referenced by std::operator<<(), and fsdict::Interpretation::print().
std::wstring fsdict::Instruction::toString () const
Referenced by fsdict::TestPattern::testInstruction().
size_t fsdict::Instruction::parseFromString (std::wstring const & str, size_t offset = 0)
Converts a string as produced by toString() back into the data structure.
Referenced by fsdict::Interpretation::parseFromString(), and fsdict::TestPattern::testInstruction().
void fsdict::Instruction::applyTo (std::wstring * str, int direction = 1) const
apply the instruction to the string passed as pointer argument
Parameters:
in/out] str the string that is to be changed by the instruction
[in] If set to -1, replaces right sides for left sides
Note that at the moment the method does not check if the instruction is applicable to str, i.e. it does not check if the left sides of the patterns really occur in str at the given positions. If the instruction specifies a transformation beyond the word border, most likely an exception will be thrown.
Todo:
make this method more secure, at least handle the exception that are maybe thrown by std::wstring::replace
bool fsdict::Instruction::containsPattern (Pattern const & pat) const
return true if the Instruction contains the given pattern.
In the current implementation this needs a linear run through the instruction.
The documentation for this class was generated from the following files:
fsdict/Pattern/Instruction.h
fsdict/Pattern/Instruction.cxx