FSDict: fsdict::TestGetopt Class Reference
fsdict::TestGetopt Class Reference
#include <TestGetopt.h>
Public Member Functions
void run ()
void testBasics ()
test the basic functionality
void testSpecified ()
void testFailure ()
test the basic functionality
Member Function Documentation
void fsdict::TestGetopt::run ()
void fsdict::TestGetopt::testBasics ()
test the basic functionality
Referenced by run().
void fsdict::TestGetopt::testSpecified ()
Referenced by main(), and run().
void fsdict::TestGetopt::testFailure ()
test the basic functionality
Referenced by run().
The documentation for this class was generated from the following file:
fsdict/Getopt/Test/TestGetopt.h