FSDict: fsdict::MinDic< AnnType >::State Class Reference
fsdict::MinDic< AnnType >::State Class Reference
This class provides a much easier interface to the MinDic if the guts of the automaton have to be explored state- and transition-wise.
#include <MinDic.h>
Public Member Functions
State (const MinDic< AnnType > &minDic)
bool walk (wchar_t c)
bool isValid ()
bool hasTransition (wchar_t c) const
returns true iff current state has a transition labelled with the given character.
State getTransTarget (wchar_t c) const
State getTransTarget (wchar_t const *str) const
const wchar_t * getSusoString () const
returns a c-string containing all characters which are the label of a transition leaving the current state
size_t getPerfHashValue () const
StateId_t getStateID () const
returns the internal id number of the curent state
bool isFinal () const
returns true iff the current state is a final state
const AnnType & getAnnotation ()
Detailed Description
template<class AnnType = int>
class fsdict::MinDic< AnnType >::State
This class provides a much easier interface to the MinDic if the guts of the automaton have to be explored state- and transition-wise.
It is best to think of a State -object as a pawn in a board game. By using MinDic's getRootState() you receive a pawn positioned at the automaton's root state. From there you can either move it along-side a transition using walk() or request a new pawn using getTransitionTarget().
Constructor & Destructor Documentation
template<class AnnType = int> fsdict::MinDic< AnnType >::State::State (const MinDic< AnnType > & minDic) [inline]
Parameters:
a reference to the MinDic the State belongs to.
Referenced by fsdict::MinDic< AnnType >::State::getStateID(), and fsdict::MinDic< AnnType >::State::walk().
Member Function Documentation
template<class AnnType = int> bool fsdict::MinDic< AnnType >::State::walk (wchar_t c) [inline]
Parameters:
c
template<class AnnType = int> bool fsdict::MinDic< AnnType >::State::isValid () [inline]
Referenced by fsdict::MinDic< AnnType >::State::hasTransition().
template<class AnnType = int> bool fsdict::MinDic< AnnType >::State::hasTransition (wchar_t c) const [inline]
returns true iff current state has a transition labelled with the given character.
Parameters:
c
template<class AnnType = int> State fsdict::MinDic< AnnType >::State::getTransTarget (wchar_t c) const [inline]
template<class AnnType = int> State fsdict::MinDic< AnnType >::State::getTransTarget (wchar_t const * str) const [inline]
template<class AnnType = int> const wchar_t* fsdict::MinDic< AnnType >::State::getSusoString () const [inline]
returns a c-string containing all characters which are the label of a transition leaving the current state
Referenced by fsdict::MinDic< AnnType >::TokenIterator::operator*().
template<class AnnType = int> size_t fsdict::MinDic< AnnType >::State::getPerfHashValue () const [inline]
See also:
perfHashValue_
template<class AnnType = int> StateId_t fsdict::MinDic< AnnType >::State::getStateID () const [inline]
returns the internal id number of the curent state
template<class AnnType = int> bool fsdict::MinDic< AnnType >::State::isFinal () const [inline]
returns true iff the current state is a final state
template<class AnnType = int> const AnnType& fsdict::MinDic< AnnType >::State::getAnnotation () [inline]
The documentation for this class was generated from the following file:
fsdict/MinDic/MinDic.h