FSDict: TransTable Class Reference
TransTable Class Reference
Public Member Functions
template<>
StateId_t walkPerfHash (StateId_t state, char16 c, size_t &perfHashValue) const
template<>
StateId_t walkStrPerfHash (StateId_t state, const wchar_t *str, size_t &perfHashValue) const
template<>
StateId_t findSlot (const TempState &state)
template<>
StateId_t findSlot (const TempState &state)
template<>
StateId_t storeTempState (TempState &state)
template<>
StateId_t storeTempState (TempState &state)
template<>
bool compareStates (const TempState &temp, StateId_t comp) const
compare a temporary state to a compressed one.
template<>
size_t count (StateId_t pos) const
template<>
void toDot () const
template<>
void doAnalysis () const
Member Function Documentation
template<> StateId_t TransTable< TOKDIC >::walkPerfHash (StateId_t state, char16 c, size_t & perfHashValue) const [inline]
Referenced by walkStrPerfHash().
template<> StateId_t TransTable< TOKDIC >::walkStrPerfHash (StateId_t state, const wchar_t * str, size_t & perfHashValue) const [inline]
template<> StateId_t TransTable< BASIC >::findSlot (const TempState & state) [inline]
Referenced by storeTempState().
template<> StateId_t TransTable< TOKDIC >::findSlot (const TempState & state) [inline]
template<> StateId_t TransTable< BASIC >::storeTempState (TempState & state) [inline]
template<> StateId_t TransTable< TOKDIC >::storeTempState (TempState & state) [inline]
template<CellType CellTypeValue> bool TransTable::compareStates (const TempState & temp, StateId_t comp) const [inline]
compare a temporary state to a compressed one.
return iff both are equivalent w.r.t their outgoing transitions
template<> size_t TransTable< TOKDIC >::count (StateId_t pos) const [inline]
template<> void TransTable< TOKDIC >::toDot () const [inline]
Referenced by main().
template<> void TransTable< TOKDIC >::doAnalysis () const [inline]
Reimplemented in fsdict::MinDic2, fsdict::MinDicString, fsdict::MinDic<>, and fsdict::MinDic< AnnType_t >.
Referenced by main().
The documentation for this class was generated from the following files:
fsdict/MinDic/MinDic.h
fsdict/TransTable/TransTable.cxx