FSDict: fsdict::Vaam< MinDicType > Class Template Reference
fsdict::Vaam< MinDicType > Class Template Reference
Vaam is a module for approximate matching in large dictionaries, considering spelling variants (defined with a set of rewrite patterns) and also spelling errors (using levenshtein distance).
#include <Vaam.h>
Classes
class CandidateReceiver
A straight-forward implementation of the interface above.
class Position
class Stack
class StackItem
Public Types
typedef MinDicType MinDic_t
The type of MinDic used as base dictionary.
Public Member Functions
Constructors
Vaam (const MinDic_t &baseDic, const char *patternFile)
A trivial construtor, taking the input ressources as arguments.
Configuration
void setDistance (size_t d)
In addition to pattern applications, allow fuzzy search with distance up to d.
void setMinNrOfPatterns (size_t n)
restrict allowed number of pattern applications to greater or equal than n
void setMaxNrOfPatterns (size_t n)
restrict allowed number of pattern applications to less or equal than n
void setBaseDic (MinDic_t const &baseDic)
set the base dictionary.
void setFilterDic (iDictionary< int > const &filterDic)
set a filter dictionary.
void setCaseMode (Global::CaseMode caseMode)
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Usage/ Queries
bool query (std::wstring const &word, iInterpretationReceiver *interpretations) const
query a word to get possible interpretations as a variant.
Static Public Attributes
static const size_t INFINITE = (size_t)-1
Detailed Description
template<typename MinDicType = MinDic< int >>
class fsdict::Vaam< MinDicType >
Vaam is a module for approximate matching in large dictionaries, considering spelling variants (defined with a set of rewrite patterns) and also spelling errors (using levenshtein distance).
Besides this class reference, please read the Vaam Manual to get an idea of how to create a Vaam object, how to send queries and how to interpret Vaam's answer.
As input the tool needs
a wordList baseDic compiled as FSA (use the tool compileMD to get such an automaton from a word list.
a file containing a list of patterns, one per line. A line containing 't th' indicates that a 't' in baseDic could be transformed to 'th'.
a threshold maxNrOfPatterns specifying the maximum number of pattern applications in one word (default: 1000, which is near to infinite).
a distance threshold distance specifying the maximum number of edit operations allowed on top of the application of variant patterns (default: 0, allow variant patterns only).
Definition of the output:
We define a so-called hypothetical dictionary hypotheticalDic that contains all spelling variants which can be obtained by applying a sequence of up to maxNrOfPatterns variant patterns to any word of baseDic. One entry of hypotheticalDic is a triple {<word,baseWord,instruction>} where instruction is the above mentioned sequence to get the variant word from the original word baseWord from baseDic.
For a query q the algorithm returns all such triples {<word,baseWord,instruction>} from hypotheticalDic where the standard levenshtein distance between word and q does not exceed
See also:
fsdict::Interpretation, fsdict::Instruction, fsdict::PosPattern, fsdict::Pattern
Author:
Ulrich Reffle, 2008
Member Typedef Documentation
template<typename MinDicType = MinDic< int >> typedef MinDicType fsdict::Vaam< MinDicType >::MinDic_t
The type of MinDic used as base dictionary.
Note that other dictionaries used here (e.g. the filterDic) are not necessarily of this type.
Constructor & Destructor Documentation
template<typename MinDicType = MinDic< int >> fsdict::Vaam< MinDicType >::Vaam (const MinDic_t & baseDic, const char * patternFile)
A trivial construtor, taking the input ressources as arguments.
Parameters:
baseDic a reference to a MinDic_t that serves as baseDic
patternFile path to a file containing the spelling variant patterns (see class description for some more details).
Member Function Documentation
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setDistance (size_t d) [inline]
In addition to pattern applications, allow fuzzy search with distance up to d.
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setMinNrOfPatterns (size_t n) [inline]
restrict allowed number of pattern applications to greater or equal than n
Referenced by fsdict::TestVaam::testBasics().
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setMaxNrOfPatterns (size_t n) [inline]
restrict allowed number of pattern applications to less or equal than n
Referenced by main(), and fsdict::TestVaam::testBasics().
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setBaseDic (MinDic_t const & baseDic) [inline]
set the base dictionary.
This restricts output words to words NOT present in this filterDic.
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setFilterDic (iDictionary< int > const & filterDic) [inline]
set a filter dictionary.
This restricts output words to words NOT present in this filterDic.
Referenced by fsdict::TestVaam::testBasics().
template<typename MinDicType = MinDic< int >> void fsdict::Vaam< MinDicType >::setCaseMode (Global::CaseMode caseMode) [inline]
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Parameters:
caseMode
Referenced by fsdict::TestVaam::testCaseMode().
template<typename MinDicType = MinDic< int >> bool fsdict::Vaam< MinDicType >::query (std::wstring const & word, iInterpretationReceiver * interpretations) const [inline]
query a word to get possible interpretations as a variant.
You can write your own class that implements the interface iCandidateReceiver to receive all answers, but you can also use Vaam's subclass CandidateReceiver.
Returns:
true iff at least one answer was found
Referenced by main(), fsdict::TestVaam::testBasics(), fsdict::TestVaam::testCaseMode(), and fsdict::TestVaam::testWordBorders().
Member Data Documentation
template<typename MinDicType = MinDic< int >> const size_t fsdict::Vaam< MinDicType >::INFINITE = (size_t)-1 [static]
The documentation for this class was generated from the following file:
fsdict/Vaam/Vaam.h