FSDict: fsdict::exceptions::fsdictException Class Reference
fsdict::exceptions::fsdictException Class Reference
#include <Global.h>
Public Member Functions
fsdictException ()
fsdictException (const std::string &msg)
virtual ~fsdictException () throw ()
virtual const char * what () const throw ()
Constructor & Destructor Documentation
fsdict::exceptions::fsdictException::fsdictException () [inline]
Referenced by fsdict::Getopt::Exception::Exception().
fsdict::exceptions::fsdictException::fsdictException (const std::string & msg) [inline]
virtual fsdict::exceptions::fsdictException::~fsdictException () throw () [inline, virtual]
Member Function Documentation
virtual const char* fsdict::exceptions::fsdictException::what () const throw () [inline, virtual]
Referenced by fsdict::Getopt::Exception::Exception(), and main().
The documentation for this class was generated from the following file:
fsdict/Global.h