FSDict: fsdict::ComputeInstruction Class Reference
fsdict::ComputeInstruction Class Reference
Computes the weighted levenshtein distance of two words.
#include <ComputeInstruction.h>
Classes
class MatrixItem
class PatternTypeChain
Public Member Functions
ComputeInstruction ()
Constructor.
~ComputeInstruction ()
Destructor.
bool computeInstruction (std::wstring const &wCorr, std::wstring const &wErr, std::vector< Instruction > *instruction=0)
Computes the weight levenshtein distance of two words.
void connectPatternProbabilities (PatternProbabilities const &levW)
Creates a connection to a LevenshteinProbabilities object.
void setMaxNumberOfInstructions (size_t n)
void setDebug (bool d)
Sets debug_.
Detailed Description
Computes the weighted levenshtein distance of two words.
Author:
Nurhan Sayhan, Musa Ilker Hatipoglu, Ahmet Saglam
Constructor & Destructor Documentation
fsdict::ComputeInstruction::ComputeInstruction ()
Constructor.
Todo:
Find a good, dynamic solution here!
fsdict::ComputeInstruction::~ComputeInstruction ()
Destructor.
Member Function Documentation
bool fsdict::ComputeInstruction::computeInstruction (std::wstring const & wCorr, std::wstring const & wErr, std::vector< Instruction > * instruction = 0)
Computes the weight levenshtein distance of two words.
Parameters:
wCorr The correct word
wErr The incorrect word
[out] instructions is a pointer to a vector of instructions, which is filled with all (equally) best ways to transform the strings.
Referenced by fsdict::TestComputeInstruction::testBasics(), and fsdict::TestComputeInstruction::testProfilerSetting().
void fsdict::ComputeInstruction::connectPatternProbabilities (fsdict::PatternProbabilities const & patternProbabilities)
Creates a connection to a LevenshteinProbabilities object.
Referenced by fsdict::TestComputeInstruction::testBasics(), and fsdict::TestComputeInstruction::testProfilerSetting().
void fsdict::ComputeInstruction::setMaxNumberOfInstructions (size_t n) [inline]
void fsdict::ComputeInstruction::setDebug (bool d)
Sets debug_.
Referenced by fsdict::TestComputeInstruction::testBasics(), and fsdict::TestComputeInstruction::testProfilerSetting().
The documentation for this class was generated from the following files:
fsdict/Pattern/ComputeInstruction.h
fsdict/Pattern/ComputeInstruction.cxx