FSDict: fsdict::TestUTF8Locale Class Reference
fsdict::TestUTF8Locale Class Reference
#include <TestUTF8Locale.h>
Public Member Functions
void run ()
void testBasics ()
test the basic methods
void testSTDIO ()
Member Function Documentation
void fsdict::TestUTF8Locale::run ()
Referenced by main().
void fsdict::TestUTF8Locale::testBasics ()
test the basic methods
Referenced by run().
void fsdict::TestUTF8Locale::testSTDIO ()
Referenced by run().
The documentation for this class was generated from the following file:
fsdict/UTF8Locale/Test/TestUTF8Locale.h