FSDict: fsdict::MSMatch< Mode > Class Template Reference
fsdict::MSMatch< Mode > Class Template Reference
MSMatch provides approximate matching in large dictionaries using determinstic Levenshtein automata.
#include <MSMatch.h>
Public Types
typedef MinDic< int > MinDic_t
The datatype returned by the method getFWDic().
Public Member Functions
MSMatch (size_t k=0)
Create an MSMatch object with a levenshtein threshold k and a path specifying a file with a compiled FBDic.
~MSMatch ()
void initialize ()
Some initialization steps shared by all constructors.
void setMinDic (MinDic_t const &minDic)
void setFBDic (FBDic<> const &fbDic)
void setDistance (size_t dist)
bool query (const wchar_t *pattern, LevFilter::CandidateReceiver &candReceiver)
compute candidates for the given query patterns; store the cands in the candReceiver object.
const MinDic_t & getFWDic () const
returns a reference to the used dictionary.
void setCaseMode (Global::CaseMode caseMode)
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Static Public Member Functions
static size_t getMaximumDistance ()
returns the highest threshold to be set.
Detailed Description
template<MSMatchMode Mode = STANDARD>
class fsdict::MSMatch< Mode >
MSMatch provides approximate matching in large dictionaries using determinstic Levenshtein automata.
It is an implementation of the concepts described in "S. Mihov and K. Schulz. Fast approximate search in large dictionaries. Computational Linguistics, 30, 2004." Basically the implementation is derived from a C-implementation of Stoyan Mihov.
It uses the universal levenshtein automaton that is implemented in class LevDEA.
MSMatch implements the interface LevFilter, that is, it provides a method query taking a word as input and a CandidateReceiver as output argument. To use MSMatch, just implement a CandidateReceiver for your needs.
See also:
fsdict::LevDEA, fsdict::LevFilter, fsdict::LevFilter::CandidateReceiver
Todo:
At the moment the levenshtein threshold can only be set once at construction. It should be easy to provide some method like setDistance() to change this anytime.
remove fixed-length string components. Change interface to std::wstring
Author:
Ulrich Reffle, <uli@cis.uni-muenchen.de>
Date:
2006
Member Typedef Documentation
template<MSMatchMode Mode = STANDARD> typedef MinDic< int > fsdict::MSMatch< Mode >::MinDic_t
The datatype returned by the method getFWDic().
Constructor & Destructor Documentation
template<MSMatchMode Mode = STANDARD> fsdict::MSMatch< Mode >::MSMatch (size_t k = 0) [inline]
Create an MSMatch object with a levenshtein threshold k and a path specifying a file with a compiled FBDic.
Parameters:
k the levenshtein threshold: MSMatch will extract candidates with distance lower or equal to k
FBDicFile a path specifying a file with a compiled FBDic
Referenced by fsdict::MSMatch< Mode >::getMaximumDistance().
template<MSMatchMode Mode = STANDARD> fsdict::MSMatch< Mode >::~MSMatch () [inline]
Referenced by fsdict::MSMatch< Mode >::getMaximumDistance().
Member Function Documentation
template<MSMatchMode Mode = STANDARD> void fsdict::MSMatch< Mode >::initialize () [inline]
Some initialization steps shared by all constructors.
Referenced by fsdict::MSMatch< Mode >::getMaximumDistance().
template<MSMatchMode Mode = STANDARD> static size_t fsdict::MSMatch< Mode >::getMaximumDistance () [inline, static]
returns the highest threshold to be set.
The setting of a higher distance (in the constructor or with setDistance()) will trigger an exception
template<MSMatchMode Mode = STANDARD> void fsdict::MSMatch< Mode >::setMinDic (MinDic_t const & minDic) [inline]
Referenced by fsdict::MSMatch< Mode >::getMaximumDistance().
template<MSMatchMode Mode = STANDARD> void fsdict::MSMatch< Mode >::setFBDic (FBDic<> const & fbDic) [inline]
template<MSMatchMode Mode = STANDARD> void fsdict::MSMatch< Mode >::setDistance (size_t dist) [inline]
template<MSMatchMode Mode = STANDARD> bool fsdict::MSMatch< Mode >::query (const wchar_t * pattern, LevFilter::CandidateReceiver & candReceiver) [inline, virtual]
compute candidates for the given query patterns; store the cands in the candReceiver object.
Parameters:
[in] pattern
[out] candReceiver
Implements fsdict::LevFilter.
template<MSMatchMode Mode = STANDARD> const MinDic_t& fsdict::MSMatch< Mode >::getFWDic () const [inline]
returns a reference to the used dictionary.
(forward, in contrast to backward as is also used for the extraction)
template<MSMatchMode Mode = STANDARD> void fsdict::MSMatch< Mode >::setCaseMode (Global::CaseMode caseMode) [inline]
Specify a case mode (one of CaseMode) to decide on the treatment of uppercased input.
Parameters:
caseMode
The documentation for this class was generated from the following file:
fsdict/MSMatch/MSMatch.h