FSDict: fsdict::Alphabet Class Reference
fsdict::Alphabet Class Reference
#include <Alphabet.h>
Classes
class Header
Public Types
typedef std::vector< wchar_t >
::const_iterator ConstCharIterator
Public Member Functions
Alphabet ()
const ConstCharIterator begin () const
ConstCharIterator end () const
void addChar (wchar_t c)
Adds a new char to the Alphabet.
bool hasChar (wchar_t c) const
void initConstruction ()
void finishConstruction ()
void loadFromStream (FILE *fi)
Loads a dumped Alphabet from the given stream.
void writeToStream (FILE *fo) const
Dumps the Alphabet in its current state to the given stream.
size_t size () const
Returns the alphabet size.
Detailed Description
Author:
Uli Reffle
Date:
2007
Member Typedef Documentation
typedef std::vector<wchar_t>::const_iterator fsdict::Alphabet::ConstCharIterator
Constructor & Destructor Documentation
fsdict::Alphabet::Alphabet ()
Member Function Documentation
const ConstCharIterator fsdict::Alphabet::begin () const [inline]
ConstCharIterator fsdict::Alphabet::end () const [inline]
void fsdict::Alphabet::addChar (wchar_t c)
Adds a new char to the Alphabet.
Todo:
trouble with signed/unsigned
Referenced by Alphabet().
bool fsdict::Alphabet::hasChar (wchar_t c) const
void fsdict::Alphabet::initConstruction ()
void fsdict::Alphabet::finishConstruction ()
void fsdict::Alphabet::loadFromStream (FILE * fi)
Loads a dumped Alphabet from the given stream.
void fsdict::Alphabet::writeToStream (FILE * fo) const
Dumps the Alphabet in its current state to the given stream.
size_t fsdict::Alphabet::size () const [inline]
Returns the alphabet size.
Referenced by getStats(), and main().
The documentation for this class was generated from the following files:
fsdict/Alphabet/Alphabet.h
fsdict/Alphabet/Alphabet.cxx