FSDict: fsdict::PatternGraph::State Class Reference
fsdict::PatternGraph::State Class Reference
#include <PatternGraph.h>
Public Types
typedef
InternalState::TransIterator iterator
Public Member Functions
State ()
State (const PatternGraph &myGraph, size_t stateIndex)
bool operator== (State const &other)
State & operator= (State const &other)
bool walk (wchar_t c)
walk in the AC-Trie.
bool walkErrorLink ()
bool walkStrict (wchar_t c)
walk in the trie only - do not use error links if walk is not possible, stay where you are
State getTransTarget (wchar_t c) const
This is equivalent to a 'walk' call, only that the state itself remains unchanged (-->const), but a copy of the target state.
iterator transBegin () const
iterator transEnd () const
size_t getPrefixLength () const
bool isFinal () const
const Replacements_t & getReplacements () const
bool isValid () const
void addTransition (wchar_t c, const State &target)
size_t getStateIndex () const
Friends
class PatternGraph
class InternalState
Member Typedef Documentation
typedef InternalState::TransIterator fsdict::PatternGraph::State::iterator
Constructor & Destructor Documentation
fsdict::PatternGraph::State::State () [inline]
fsdict::PatternGraph::State::State (const PatternGraph & myGraph, size_t stateIndex) [inline]
Member Function Documentation
bool fsdict::PatternGraph::State::operator== (State const & other) [inline]
State& fsdict::PatternGraph::State::operator= (State const & other) [inline]
bool fsdict::PatternGraph::State::walk (wchar_t c) [inline]
walk in the AC-Trie.
Use error links when needed.
Returns:
the "distance" from the root to the target state
Referenced by getTransTarget(), main(), fsdict::TestVaam::testPatternGraph(), and fsdict::TestPattern::testPatternGraph().
bool fsdict::PatternGraph::State::walkErrorLink () [inline]
bool fsdict::PatternGraph::State::walkStrict (wchar_t c) [inline]
walk in the trie only - do not use error links if walk is not possible, stay where you are
Returns:
true if an appropriate transition was found
Referenced by fsdict::PatternGraph::loadPatterns(), and walk().
PatternGraph::State fsdict::PatternGraph::State::getTransTarget (wchar_t c) const [inline]
This is equivalent to a 'walk' call, only that the state itself remains unchanged (-->const), but a copy of the target state.
Referenced by fsdict::TestVaam::testPatternGraph(), and fsdict::TestPattern::testPatternGraph().
PatternGraph::State::iterator fsdict::PatternGraph::State::transBegin () const [inline]
Returns:
an iterator positioned at the first of the state's transitions
PatternGraph::State::iterator fsdict::PatternGraph::State::transEnd () const [inline]
Returns:
a past-the-end iterator for the state's transitions
size_t fsdict::PatternGraph::State::getPrefixLength () const [inline]
Returns:
the "distance" from the root to the target state
Referenced by fsdict::PatternGraph::loadPatterns().
bool fsdict::PatternGraph::State::isFinal () const [inline]
Referenced by main(), fsdict::TestVaam::testPatternGraph(), and fsdict::TestPattern::testPatternGraph().
PatternGraph::Replacements_t const & fsdict::PatternGraph::State::getReplacements () const [inline]
Returns:
a reference to the list of replacements attached to the state (which must be final)
bool fsdict::PatternGraph::State::isValid () const [inline]
Returns:
true iff the current state is not the failstate
Referenced by walk(), and walkErrorLink().
void fsdict::PatternGraph::State::addTransition (wchar_t c, const State & target) [inline]
size_t fsdict::PatternGraph::State::getStateIndex () const [inline]
Referenced by fsdict::PatternGraph::loadPatterns(), walk(), and walkErrorLink().
Friends And Related Function Documentation
friend class PatternGraph [friend]
friend class InternalState [friend]
The documentation for this class was generated from the following file:
fsdict/Pattern/PatternGraph.h