FSDict: fsdict::UTF8Locale Class Reference
fsdict::UTF8Locale Class Reference
A locale using our own implementation of a utf8 codecvt, and a ctype facet handling umlauts and other peculiarities properly.
#include <UTF8Locale.h>
Static Public Member Functions
static UTF8Locale & Instance ()
template<typename T , typename char_type >
static T string2number (std::basic_string< char_type > const &str)
Goes the STL facet-based way to transform a string to a number.
static void wstring2string (std::wstring const &wstr, std::string &str)
converts a std::wstring into its byte-character equivalent
static void string2wstring (std::string const &str, std::wstring &wstr)
converts a std::string into its wide-character equivalent
static std::wstring string2wstring (std::string const &str)
Returns a copy of a wide string equivalent to the given narrow string.
static std::string wstring2string (std::wstring const &str)
Returns a copy of a narrow string equivalent to the given wide string.
Detailed Description
A locale using our own implementation of a utf8 codecvt, and a ctype facet handling umlauts and other peculiarities properly.
Member Function Documentation
static UTF8Locale& fsdict::UTF8Locale::Instance () [inline, static]
Referenced by fsdict::PatternWeights::loadFromFile(), string2number(), string2wstring(), fsdict::TestUTF8Locale::testBasics(), fsdict::TestUTF8Locale::testSTDIO(), fsdict::PatternWeights::writeToFile(), and wstring2string().
template<typename T , typename char_type > static T fsdict::UTF8Locale::string2number (std::basic_string< char_type > const & str) [inline, static]
Goes the STL facet-based way to transform a string to a number.
Parameters:
[in] str a string containing the number and nothing else
Throws a fsdictException if the conversion causes problems.
static void fsdict::UTF8Locale::wstring2string (std::wstring const & wstr, std::string & str) [inline, static]
converts a std::wstring into its byte-character equivalent
Parameters:
[in] wstr the input string
[out] str the output string
Referenced by fsdict::PatternSet::loadPatterns(), fsdict::Instruction::parseFromString(), fsdict::PatternSet::push_back(), fsdict::TestLevDEA::testWithInputString(), and wstring2string().
static void fsdict::UTF8Locale::string2wstring (std::string const & str, std::wstring & wstr) [inline, static]
converts a std::string into its wide-character equivalent
Parameters:
[in] str the input string
[out] wstr the output string
Referenced by fsdict::INIConfig::dump_ini(), iniparser_set(), fsdict::LevDEA::loadPattern_utf8(), main(), string2wstring(), and fsdict::TestUTF8Locale::testSTDIO().
static std::wstring fsdict::UTF8Locale::string2wstring (std::string const & str) [inline, static]
Returns a copy of a wide string equivalent to the given narrow string.
static std::string fsdict::UTF8Locale::wstring2string (std::wstring const & str) [inline, static]
Returns a copy of a narrow string equivalent to the given wide string.
The documentation for this class was generated from the following files:
fsdict/UTF8Locale/UTF8Locale.h
fsdict/UTF8Locale/UTF8Locale.cxx