FSDict: fsdict::TestPattern Class Reference
fsdict::TestPattern Class Reference
This test class subsumes tests for the classes Pattern, PosPattern and Instruction.
#include <TestPattern.h>
Public Member Functions
void testPattern ()
test the basic methods of class Pattern.
void testPatternSet ()
void testPosPattern ()
void testInstruction ()
void testInterpretation ()
void testPatternProbabilities ()
void testPatternGraph ()
void run ()
Detailed Description
This test class subsumes tests for the classes Pattern, PosPattern and Instruction.
Author:
Ulrich Reffle, 2008
Member Function Documentation
void fsdict::TestPattern::testPattern ()
test the basic methods of class Pattern.
Referenced by run().
void fsdict::TestPattern::testPatternSet ()
Referenced by run().
void fsdict::TestPattern::testPosPattern ()
Referenced by run().
void fsdict::TestPattern::testInstruction ()
Referenced by run().
void fsdict::TestPattern::testInterpretation ()
Referenced by run().
void fsdict::TestPattern::testPatternProbabilities ()
Referenced by run().
void fsdict::TestPattern::testPatternGraph ()
Referenced by run().
void fsdict::TestPattern::run ()
The documentation for this class was generated from the following file:
fsdict/Pattern/Test/TestPattern.h