FSDict: fsdict::Pattern Class Reference
fsdict::Pattern Class Reference
Pattern holds one string substitution alpha --> beta which is allowed in a certain context.
#include <Pattern.h>
Public Member Functions
Pattern ()
Constructs an empty pattern with left == right == "".
Pattern (const std::wstring &left, const std::wstring &right)
A very self-explanatory constructor.
bool operator== (const Pattern &other) const
bool operator!= (const Pattern &other) const
bool operator< (const Pattern &other) const
creates an order relation on Pattern objects, mainly to be able t ostore them in std::set etc.
void clear ()
const std::wstring & getLeft () const
get the left side of the pattern
const std::wstring & getRight () const
get the right side of the pattern
bool empty () const
returns if pattern is "empty"
void setLeft (std::wstring const &left)
void setRight (std::wstring const &right)
void strip ()
Get rid of wordBegin- and wordEnd-markers.
void print (std::wostream &os=std::wcout) const
std::wstring toString () const
Static Public Member Functions
static void setLeftRightDelimiter (wchar_t c)
Static Public Attributes
static wchar_t leftRightDelimiter_ = L':'
This value determines which symbol is used as delimiter between left and right pattern side.
Detailed Description
Pattern holds one string substitution alpha --> beta which is allowed in a certain context.
The Pattern object simply has two string components left and right. If both are empty, the pattern is something like a "neutral element", or a dummy. Then, empty() returns true. It is sometimes needed where the implementation expects a Pattern without there really being one.
Author:
Ulrich Reffle, 2008
Constructor & Destructor Documentation
fsdict::Pattern::Pattern () [inline]
Constructs an empty pattern with left == right == "".
fsdict::Pattern::Pattern (const std::wstring & left, const std::wstring & right) [inline]
A very self-explanatory constructor.
Member Function Documentation
bool fsdict::Pattern::operator== (const Pattern & other) const [inline]
bool fsdict::Pattern::operator!= (const Pattern & other) const [inline]
bool fsdict::Pattern::operator< (const Pattern & other) const [inline]
creates an order relation on Pattern objects, mainly to be able t ostore them in std::set etc.
The order is equivalent to alphabetical order of left sides, in case of equality of the right sides.
void fsdict::Pattern::clear () [inline]
Reimplemented in fsdict::PosPattern.
const std::wstring & fsdict::Pattern::getLeft () const [inline]
get the left side of the pattern
Returns:
the left side of the pattern
Referenced by fsdict::Instruction::applyTo(), fsdict::PatternWeights::getWeight(), operator<(), operator==(), print(), fsdict::PatternSet::push_back(), fsdict::TestPattern::testPattern(), fsdict::TestPattern::testPosPattern(), and toString().
const std::wstring & fsdict::Pattern::getRight () const [inline]
get the right side of the pattern
Returns:
the right side of the pattern
Referenced by fsdict::Instruction::applyTo(), fsdict::PatternWeights::getWeight(), operator<(), operator==(), print(), fsdict::PatternSet::push_back(), fsdict::TestPattern::testPattern(), fsdict::TestPattern::testPosPattern(), and toString().
bool fsdict::Pattern::empty () const [inline]
returns if pattern is "empty"
Reimplemented in fsdict::PosPattern.
Referenced by fsdict::PosPattern::empty().
void fsdict::Pattern::setLeft (std::wstring const & left) [inline]
Referenced by fsdict::PosPattern::parseFromString().
void fsdict::Pattern::setRight (std::wstring const & right) [inline]
Referenced by fsdict::PosPattern::parseFromString().
void fsdict::Pattern::strip () [inline]
Get rid of wordBegin- and wordEnd-markers.
Referenced by fsdict::Instruction::applyTo().
void fsdict::Pattern::print (std::wostream & os = std::wcout) const [inline]
Reimplemented in fsdict::PosPattern.
std::wstring fsdict::Pattern::toString () const [inline]
Reimplemented in fsdict::PosPattern.
Referenced by fsdict::PatternSet::push_back(), and fsdict::PatternGraph::toDot().
static void fsdict::Pattern::setLeftRightDelimiter (wchar_t c) [inline, static]
Referenced by main().
Member Data Documentation
wchar_t fsdict::Pattern::leftRightDelimiter_ = L':' [static]
This value determines which symbol is used as delimiter between left and right pattern side.
NOTE THAT, once you change this, it will affect the output of patterns as well as the parsing from pattern files etc.
This value is initialized with a default value in Pattern.cxx
Referenced by fsdict::PatternWeights::loadFromFile(), fsdict::PatternSet::loadPatterns(), fsdict::PosPattern::parseFromString(), fsdict::PatternWeights::print(), print(), setLeftRightDelimiter(), toString(), and fsdict::PatternWeights::writeToFile().
The documentation for this class was generated from the following files:
fsdict/Pattern/Pattern.h
fsdict/Pattern/Pattern.cxx