FSDict: fsdict::MinDic2 Class Reference
fsdict::MinDic2 Class Reference
class MinDic2 performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
#include <MinDic2.h>
Classes
class Header
class State
This class provides a much easier interface to the MinDic if the guts of the automaton have to be explored state- and transition-wise.
Public Types
typedef TransTable
< TT_STANDARD, uint16_t > TransTable_t
typedef int AnnType_t
Public Member Functions
MinDic2 (const char *dicFile=0)
Create a new MinDic.
Lookup
bool lookup (const wchar_t *key, AnnType_t *annotation=0) const
Use this function to do a convenient lookup.
bool lookup (std::wstring const &key, AnnType_t *annotation=0) const
bool hasPrefix (std::wstring const &prefix) const
State getRootState () const
Get a State object of the automaton's root/ start state.
Loading from /writing to hard disk
void loadFromFile (const char *binFile)
Load a compiled MinDic from hard disk.
void loadFromStream (FILE *fi)
Load a compiled MinDic from an open file stream.
void writeToFile (char const *binFile) const
dump MinDic automaton to a file in binary form.
void writeToStream (FILE *fo) const
dump MinDic automaton to an open file stream
Construction of a new MinDic
void compileDic (const char *txtFile)
The funtion that actually executes the computation of the trie.
void parseAnnotation (std::wstring *str, AnnType_t *annotation) const
void initConstruction ()
prepares the object for construction of a new MinDic.
void finishConstruction ()
void addToken (const wchar_t *input, const AnnType_t &value)
processes one input line: separates the key from the annotations (if present) and performs the insertion into the trie
Convenience, Information, Debug
void printDic () const
void printDic (StateId_t initState) const
extracts the trie to stdout
size_t getNrOfKeys () const
void doAnalysis () const
int getFirstAnn (StateId_t state)
This method from TransTable is blocked for MinDic2, not implemented here!
Protected Member Functions
const AnnType_t & annotationsAt (size_t n) const
Detailed Description
class MinDic2 performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
It follows an algorithm described in Jan Daciuk et. al., Incremental Construction of Minimal Acyclic Finite-State Automata, 2000.
Many ideas for the implementation are adapted from a C-program written by Stoyan Mihov.
While MinDic uses perfect hashing to store annotations with the entries, MinDic2 ...
Note that a MinDic2 inherits from TransTable and so offers all of TransTable's interface to the guts of the automaton. However this might change in the future.
Author:
Ulrich Reffle, <uli@cis.uni-muenchen.de>
Date:
Sept 2008
Member Typedef Documentation
typedef TransTable< TT_STANDARD, uint16_t > fsdict::MinDic2::TransTable_t
typedef int fsdict::MinDic2::AnnType_t
Constructor & Destructor Documentation
fsdict::MinDic2::MinDic2 (const char * dicFile = 0)
Create a new MinDic.
An optional file-path as argument invokes a call to loadFromFile.
Parameters:
a file containing a compiled MinDic. (optional; often: *.mdic)
Member Function Documentation
bool fsdict::MinDic2::lookup (const wchar_t * key, AnnType_t * annotation = 0) const [inline]
Use this function to do a convenient lookup.
If you don't need the annotation, just pass on a NULL-Pointer or omit the 2nd argument.
Parameters:
[in] key a key of the dictionary
[out] annotation a pointer where to store the found annotation. If NULL, then annotation is discarded
Returns:
true iff key was found in the dictionary
Referenced by main().
bool fsdict::MinDic2::lookup (std::wstring const & key, AnnType_t * annotation = 0) const [inline]
bool fsdict::MinDic2::hasPrefix (std::wstring const & prefix) const [inline]
State fsdict::MinDic2::getRootState () const [inline]
Get a State object of the automaton's root/ start state.
Returns:
a State object of the automaton's root/ start state.
See also:
State
void fsdict::MinDic2::loadFromFile (const char * binFile) [inline]
Load a compiled MinDic from hard disk.
Parameters:
a file containing a compiled MinDic. (often: *.mdic)
Referenced by main().
void fsdict::MinDic2::loadFromStream (FILE * fi) [inline]
Load a compiled MinDic from an open file stream.
Parameters:
fi a c-style file pointer.
void fsdict::MinDic2::writeToFile (char const * binFile) const [inline]
dump MinDic automaton to a file in binary form.
Parameters:
binFile File to write the automaton into.
Referenced by main().
void fsdict::MinDic2::writeToStream (FILE * fo) const [inline]
dump MinDic automaton to an open file stream
Parameters:
fo a c-style file pointer.
void fsdict::MinDic2::compileDic (const char * txtFile) [inline]
The funtion that actually executes the computation of the trie.
Todo:
Should this method be public??? Maybe not ...
Parameters:
txtFile The dictionary (including annotations) in txt format
Referenced by main().
void fsdict::MinDic2::parseAnnotation (std::wstring * str, AnnType_t * annotation) const [inline]
Todo:
add documentation
Referenced by main().
void fsdict::MinDic2::initConstruction () [inline]
prepares the object for construction of a new MinDic.
Call before calling addToken() for the first time.
Referenced by main().
void fsdict::MinDic2::finishConstruction () [inline]
Referenced by main().
void fsdict::MinDic2::addToken (const wchar_t * input, const AnnType_t & value) [inline]
processes one input line: separates the key from the annotations (if present) and performs the insertion into the trie
a cstring pointing to the current line
Referenced by main().
void fsdict::MinDic2::printDic () const [inline]
Referenced by main().
void fsdict::MinDic2::printDic (StateId_t initState) const [inline]
extracts the trie to stdout
size_t fsdict::MinDic2::getNrOfKeys () const [inline]
void fsdict::MinDic2::doAnalysis () const [inline]
Reimplemented from TransTable.
Referenced by main().
int fsdict::MinDic2::getFirstAnn (StateId_t state) [inline]
This method from TransTable is blocked for MinDic2, not implemented here!
const AnnType_t& fsdict::MinDic2::annotationsAt (size_t n) const [inline, protected]
The documentation for this class was generated from the following file:
fsdict/MinDic2/MinDic2.h