FSDict: fsdict/INIConfig/dictionary.h File Reference
dictionary.h File Reference
Implements a dictionary for string variables.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Classes
struct _dictionary_
Dictionary object.
Typedefs
typedef struct _dictionary_ dictionary
Dictionary object.
Functions
unsigned dictionary_hash (char const *key)
Compute the hash key for a string.
dictionary * dictionary_new (int size)
Create a new dictionary object.
void dictionary_del (dictionary *vd)
Delete a dictionary object.
char * dictionary_get (dictionary *d, char *key, char *def)
Get a value from a dictionary.
int dictionary_set (dictionary *vd, char const *key, char const *val)
Set a value in a dictionary.
void dictionary_unset (dictionary *d, char *key)
Delete a key in a dictionary.
void dictionary_dump (dictionary *d, FILE *out)
Dump a dictionary to an opened file pointer.
Detailed Description
Implements a dictionary for string variables.
Author:
N. Devillard
Date:
Sep 2007
Version:
Revision
1.12
This module implements a simple dictionary object, i.e. a list of string/string associations. This object is useful to store e.g. informations retrieved from a configuration file (ini files).
Typedef Documentation
typedef struct _dictionary_ dictionary
Dictionary object.
This object contains a list of string/string associations. Each association is identified by a unique string key. Looking up values in the dictionary is speeded up by the use of a (hopefully collision-free) hash function.
Function Documentation
unsigned dictionary_hash (char const * key)
Compute the hash key for a string.
Parameters:
key Character string to use for key.
Returns:
1 unsigned int on at least 32 bits.
This hash function has been taken from an Article in Dr Dobbs Journal. This is normally a collision-free function, distributing keys evenly. The key is stored anyway in the struct so that collision can be avoided by comparing the key itself in last resort.
dictionary* dictionary_new (int size)
Create a new dictionary object.
Parameters:
size Optional initial size of the dictionary.
Returns:
1 newly allocated dictionary objet.
This function allocates a new dictionary object of given size and returns it. If you do not know in advance (roughly) the number of entries in the dictionary, give size=0.
Referenced by iniparser_load().
void dictionary_del (dictionary * vd)
Delete a dictionary object.
Parameters:
d dictionary object to deallocate.
Returns:
void
Deallocate a dictionary object and all memory associated to it.
Referenced by iniparser_freedict(), and iniparser_load().
char* dictionary_get (dictionary * d, char * key, char * def)
Get a value from a dictionary.
Parameters:
d dictionary object to search.
key Key to look for in the dictionary.
def Default value to return if key not found.
Returns:
1 pointer to internally allocated character string.
This function locates a key in a dictionary and returns a pointer to its value, or the passed 'def' pointer if no such key can be found in dictionary. The returned character pointer points to data internal to the dictionary object, you should not try to free it or modify it.
Referenced by iniparser_getstring().
int dictionary_set (dictionary * vd, char const * key, char const * val)
Set a value in a dictionary.
Parameters:
d dictionary object to modify.
key Key to modify or add.
val Value to add.
Returns:
int 0 if Ok, anything else otherwise
If the given key is found in the dictionary, the associated value is replaced by the provided one. If the key cannot be found in the dictionary, it is added to it.
It is Ok to provide a NULL value for val, but NULL values for the dictionary or the key are considered as errors: the function will return immediately in such a case.
Notice that if you dictionary_set a variable to NULL, a call to dictionary_get will return a NULL value: the variable will be found, and its value (NULL) is returned. In other words, setting the variable content to NULL is equivalent to deleting the variable from the dictionary. It is not possible (in this implementation) to have a key in the dictionary without value.
This function returns non-zero in case of failure.
Referenced by iniparser_load(), and iniparser_set().
void dictionary_unset (dictionary * d, char * key)
Delete a key in a dictionary.
Parameters:
d dictionary object to modify.
key Key to remove.
Returns:
void
This function deletes a key in a dictionary. Nothing is done if the key cannot be found.
Referenced by iniparser_unset().
void dictionary_dump (dictionary * d, FILE * out)
Dump a dictionary to an opened file pointer.
Parameters:
d Dictionary to dump
f Opened file pointer.
Returns:
void
Dumps a dictionary onto an opened file pointer. Key pairs are printed out as [Key]=[Value], one per line. It is Ok to provide stdout or stderr as output file pointers.