FSDict: fsdict Namespace Reference
fsdict Namespace Reference
This namespace covers a system of modules for string processing.
Namespaces
namespace Global
namespace exceptions
Classes
class Alphabet
class UTF8_Codecvt
This is a custom implementation of a codecvt facet for utf-8, as it does not seem to be present on all systems (especially WIN).
class FBDic
Class FBDic ("Foward-Backward-Dictionary") covers a dictionary and its reversed variant in one object and also, more importantly, in one binary file on the hard disk.
class TestFBDic
class FBDicString
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
class Getopt
A class for the parsing of command line arguments.
class TestGetopt
class Hash
Hash provides a hash table which stores and finds c-strings.
class iDictionary
class INIConfig
INIConfig is an object-oriented interface to the c-style "iniparser" to parse simple ini-style configuration files.
class TestINIConfig
class AutData< 0 >
class AutData< 1 >
class AutData< 2 >
class LevDEA
LevDEA gives access to deterministic levenshtein automata.
class TestLevDEA
class LevDistance
Compute standard Levenshtein distance given two strings.
class TestLevDistance
class LevFilter
class TestCtype_OldGerman
class MinDic
class MinDic performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
class StateHash
Statehash is a hashtable to store states of a MinDic during dictionary construction.
class TestMinDic
class MinDic2
class MinDic2 performs the construction and usage of minimal acyclic finite state automata for large finite dictionaries.
class MinDicString
class provides the storage and lookup of huge dictionaries whose entries are annotated with a string-value of arbitrary length.
class MSMatch
MSMatch provides approximate matching in large dictionaries using determinstic Levenshtein automata.
class ComputeInstruction
Computes the weighted levenshtein distance of two words.
class Instruction
Instruction is a std::vector< PosPattern>, and it's an instruction in the sense we use the word in connection with spelling variants.
class Interpretation
This class is something like a container class to store one interpretation of some string as the spelling variant (and/or erroneous variant) of some other string.
class Pattern
Pattern holds one string substitution alpha --> beta which is allowed in a certain context.
class PatternGraph
A specialised variant of the Aho-Corasick trie to search in the set of left or right sides of a PatternSet.
class PatternSet
A collection of patterns that should be available in some context.
class PatternWeights
class PosPattern
the Pattern class is simply enriched by a member variable indicating a position inside a word
class TestComputeInstruction
This test class subsumes tests for the classes Pattern, PosPattern and Instruction.
class TestPattern
This test class subsumes tests for the classes Pattern, PosPattern and Instruction.
class TestPatternWeights
This test class tests class PatternWeights.
class ResultSet
A container class for candidate sets extracted by a LevFilter object.
class Stopwatch
class Cell< TT_PERFHASH, InternalCharType__, SizeType__ >
In this implementation, the member type_ encodes the function of the cell: 0: free cell 1: transition cell 2: state cell 3: final state cell.
class Cell< TT_STANDARD, InternalCharType__, SizeType__ >
In this implementation, the member type_ encodes the function of the cell: 0: free cell 1: transition cell 2: state cell 3: final state cell.
class TempState
TempState is to be used to construct a state of the automaton bit by bit.
class TransTable< TT_PERFHASH, InternalCharType__, SizeType__ >
class TransTable< TT_STANDARD, InternalCharType__, SizeType__ >
class TestUTF8Locale
class UTF8Locale
A locale using our own implementation of a utf8 codecvt, and a ctype facet handling umlauts and other peculiarities properly.
class TestVaam
class iInterpretationReceiver
iInterpretationReceiver is an interface to be implemented by classes which are supposed to receive results from the Vaam matcher (see below).
class Vaam
Vaam is a module for approximate matching in large dictionaries, considering spelling variants (defined with a set of rewrite patterns) and also spelling errors (using levenshtein distance).
class TestVal
class Val
Typedefs
typedef unsigned short char16
typedef wchar_t char32
typedef unsigned char uchar
typedef unsigned int uint_t
typedef int bits32
typedef unsigned long long ulong_t
typedef unsigned long long bits64
typedef unsigned int StateId_t
typedef fsdict::PatternWeights PatternProbabilities
typedef Instruction Trace
Enumerations
enum CellType { SLIM, BASIC, TOKDIC }
enum MSMatchMode { STANDARD, FW_BW }
enum TransTableType { TT_STANDARD, TT_PERFHASH }
Functions
CPPUNIT_TEST_SUITE_REGISTRATION (TestFBDic)
CPPUNIT_TEST_SUITE_REGISTRATION (TestGetopt)
template<typename char_t >
size_t split (std::basic_string< char_t > const &str, char_t delimiter, std::vector< std::basic_string< char_t > > *pieces)
Split a string using the given delimiter and collect the pieces in the given vector.
CPPUNIT_TEST_SUITE_REGISTRATION (TestINIConfig)
CPPUNIT_TEST_SUITE_REGISTRATION (TestLevDEA)
template<typename T >
std::string toString (const T &value)
CPPUNIT_TEST_SUITE_REGISTRATION (TestLevDistance)
CPPUNIT_TEST_SUITE_REGISTRATION (TestCtype_OldGerman)
CPPUNIT_TEST_SUITE_REGISTRATION (TestMinDic)
CPPUNIT_TEST_SUITE_REGISTRATION (TestComputeInstruction)
CPPUNIT_TEST_SUITE_REGISTRATION (TestPattern)
void populatePatternSet (PatternSet &patternSet)
CPPUNIT_TEST_SUITE_REGISTRATION (TestPatternWeights)
CPPUNIT_TEST_SUITE_REGISTRATION (TestUTF8Locale)
CPPUNIT_TEST_SUITE_REGISTRATION (TestVaam)
CPPUNIT_TEST_SUITE_REGISTRATION (TestVal)
Detailed Description
This namespace covers a system of modules for string processing.
Represents one unit of the sparse table implementation in TransTable.
Todo:
rename typedefs to "fasel_t"
Author:
Uli Reffle <uli@reffle.de>
Date:
Jan 2007
Typedef Documentation
typedef unsigned short fsdict::char16
typedef wchar_t fsdict::char32
typedef unsigned char fsdict::uchar
typedef unsigned int fsdict::uint_t
typedef int fsdict::bits32
typedef unsigned long long fsdict::ulong_t
typedef unsigned long long fsdict::bits64
typedef unsigned int fsdict::StateId_t
typedef fsdict::PatternWeights fsdict::PatternProbabilities
typedef Instruction fsdict::Trace
Enumeration Type Documentation
enum fsdict::CellType
Enumerator:
SLIM
just 4 bytes per transition (currently not implemented)
BASIC
8 bytes per transition, multiple values can be stored inside states
TOKDIC
12 bytes per transition; perfect hashing (ph) provides offset for a single value, "SuperSonic(suso) Mode" provides for each state a string of available transition-labels designed to hold huge token dictionaries with some frequency (or other) score
enum fsdict::MSMatchMode
Enumerator:
STANDARD
FW_BW
enum fsdict::TransTableType
Enumerator:
TT_STANDARD
TT_PERFHASH
Function Documentation
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestFBDic)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestGetopt)
template<typename char_t > size_t fsdict::split (std::basic_string< char_t > const & str, char_t delimiter, std::vector< std::basic_string< char_t > > * pieces) [inline]
Split a string using the given delimiter and collect the pieces in the given vector.
Parameters:
[in] str the input string
[in] delimiter The delimiter symbol
[out] A pointer to the result vector
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestINIConfig)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestLevDEA)
template<typename T > std::string fsdict::toString (const T & value) [inline]
Referenced by fsdict::TestLevDEA::testWithInputString().
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestLevDistance)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestCtype_OldGerman)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestMinDic)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestComputeInstruction)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestPattern)
void fsdict::populatePatternSet (PatternSet & patternSet)
Referenced by fsdict::TestPattern::testPatternGraph(), and fsdict::TestPattern::testPatternSet().
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestPatternWeights)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestUTF8Locale)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestVaam)
fsdict::CPPUNIT_TEST_SUITE_REGISTRATION (TestVal)